/* Generated by Arkchemy's recomp tool. Do not edit by hand. */
#include "ppc_runtime.h"

void t9_bss_large_fill_and_check(PpcContext *ctx);
void t9_bss_large_dispatch(PpcContext *ctx, uint32_t addr);

void t9_bss_large_init_globals(PpcContext *ctx) {
  ppc_store_u8(ctx, 9395u, 111);
  ppc_store_u8(ctx, 9399u, 222);
  ppc_store_u8(ctx, 9402u, 1);
  ppc_store_u8(ctx, 9403u, 77);
  ppc_store_u8(ctx, 9406u, 1);
  ppc_store_u8(ctx, 9407u, 188);
}

void t9_bss_large_run_static_initializers(PpcContext *ctx) {
}

void t9_bss_large_dispatch(PpcContext *ctx, uint32_t addr) {
  switch (addr) {
    case 0u: t9_bss_large_fill_and_check(ctx); return;
  }
}

void t9_bss_large_fill_and_check(PpcContext *ctx) {
  g_ppc_last_caller_lr = ctx->lr;
  g_ppc_current_pc = 0x0u; g_ppc_fn_call_count++;
  for (int __w = 0; __w < ARKCHEMY_WATCH_SLOTS; __w++) { if (g_ppc_current_pc == g_ppc_watch[__w].pc) { g_ppc_watch[__w].r3 = ctx->r[3]; g_ppc_watch[__w].r4 = ctx->r[4]; g_ppc_watch[__w].r5 = ctx->r[5]; g_ppc_watch[__w].r6 = ctx->r[6]; g_ppc_watch[__w].hit_count++; g_ppc_watch[__w].last_hit_call_count = g_ppc_fn_call_count; } }
  /* 0: stwu r1, -0x20(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)-32, ctx->r[1]);
  ctx->r[1] = ctx->r[1] + (int32_t)-32;
  /* 4: stw r31, 0x1c(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)28, ctx->r[31]);
  /* 8: mr r31, r1 */
  ctx->r[31] = ctx->r[1];
  /* c: li r3, 0 */
  ctx->r[3] = (uint32_t)(int32_t)0;
  /* 10: stw r3, 0x18(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)24, ctx->r[3]);
  /* 14: b 0x18 */
  goto L_18;
  L_18: ;
  /* 18: lwz r3, 0x18(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)24);
  /* 1c: cmpwi r3, 0x12b */
  ppc_cmpw(ctx, (int32_t)ctx->r[3], 299);
  /* 20: bgt 0x54 */
  if (ctx->cr0_gt) goto L_54;
  /* 24: b 0x28 */
  goto L_28;
  L_28: ;
  /* 28: lwz r4, 0x18(r31) */
  ctx->r[4] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)24);
  /* 2c: addi r3, r4, 1 */
  ctx->r[3] = ctx->r[4] + (uint32_t)(int32_t)1;
  /* 30: slwi r5, r4, 2 */
  ctx->r[5] = ctx->r[4] << 2;
  /* 34: lis r4, 0 */
  ctx->r[4] = 8192u; /* &.bss+0 */
  /* 38: addi r4, r4, 0 */
  ctx->r[4] = ctx->r[4];
  /* 3c: stwx r3, r4, r5 */
  ppc_store_u32(ctx, ctx->r[4] + ctx->r[5], ctx->r[3]);
  /* 40: b 0x44 */
  goto L_44;
  L_44: ;
  /* 44: lwz r3, 0x18(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)24);
  /* 48: addi r3, r3, 1 */
  ctx->r[3] = ctx->r[3] + (uint32_t)(int32_t)1;
  /* 4c: stw r3, 0x18(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)24, ctx->r[3]);
  /* 50: b 0x18 */
  goto L_18;
  L_54: ;
  /* 54: li r3, 0 */
  ctx->r[3] = (uint32_t)(int32_t)0;
  /* 58: stw r3, 0x14(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)20, ctx->r[3]);
  /* 5c: stw r3, 0x10(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)16, ctx->r[3]);
  /* 60: b 0x64 */
  goto L_64;
  L_64: ;
  /* 64: lwz r3, 0x10(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)16);
  /* 68: cmpwi r3, 0x12b */
  ppc_cmpw(ctx, (int32_t)ctx->r[3], 299);
  /* 6c: bgt 0xa8 */
  if (ctx->cr0_gt) goto L_a8;
  /* 70: b 0x74 */
  goto L_74;
  L_74: ;
  /* 74: lwz r3, 0x10(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)16);
  /* 78: slwi r4, r3, 2 */
  ctx->r[4] = ctx->r[3] << 2;
  /* 7c: lis r3, 0 */
  ctx->r[3] = 8192u; /* &.bss+0 */
  /* 80: addi r3, r3, 0 */
  ctx->r[3] = ctx->r[3];
  /* 84: lwzx r4, r3, r4 */
  ctx->r[4] = ppc_load_u32(ctx, ctx->r[3] + ctx->r[4]);
  /* 88: lwz r3, 0x14(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)20);
  /* 8c: add r3, r3, r4 */
  ctx->r[3] = ctx->r[3] + ctx->r[4];
  /* 90: stw r3, 0x14(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)20, ctx->r[3]);
  /* 94: b 0x98 */
  goto L_98;
  L_98: ;
  /* 98: lwz r3, 0x10(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)16);
  /* 9c: addi r3, r3, 1 */
  ctx->r[3] = ctx->r[3] + (uint32_t)(int32_t)1;
  /* a0: stw r3, 0x10(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)16, ctx->r[3]);
  /* a4: b 0x64 */
  goto L_64;
  L_a8: ;
  /* a8: lwz r3, 0x14(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)20);
  /* ac: lis r4, 0 */
  ctx->r[4] = 9392u; /* &.rodata+0 */
  /* b0: addi r4, r4, 0 */
  ctx->r[4] = ctx->r[4];
  /* b4: lwz r4, 8(r4) */
  ctx->r[4] = ppc_load_u32(ctx, ctx->r[4] + (int32_t)8);
  /* b8: add r3, r3, r4 */
  ctx->r[3] = ctx->r[3] + ctx->r[4];
  /* bc: lwz r31, 0x1c(r1) */
  ctx->r[31] = ppc_load_u32(ctx, ctx->r[1] + (int32_t)28);
  /* c0: addi r1, r1, 0x20 */
  ctx->r[1] = ctx->r[1] + (uint32_t)(int32_t)32;
  /* c4: blr  */
  return;
}
