/* Generated by Arkchemy's recomp tool. Do not edit by hand. */
#include "ppc_runtime.h"

void t6_andi_lwzu_compute(PpcContext *ctx);
void t6_andi_lwzu_dispatch(PpcContext *ctx, uint32_t addr);

void t6_andi_lwzu_init_globals(PpcContext *ctx) {
}

void t6_andi_lwzu_run_static_initializers(PpcContext *ctx) {
}

void t6_andi_lwzu_dispatch(PpcContext *ctx, uint32_t addr) {
  switch (addr) {
    case 0u: t6_andi_lwzu_compute(ctx); return;
  }
}

void t6_andi_lwzu_compute(PpcContext *ctx) {
  g_ppc_last_caller_lr = ctx->lr;
  g_ppc_current_pc = 0x0u; g_ppc_fn_call_count++;
  for (int __w = 0; __w < ARKCHEMY_WATCH_SLOTS; __w++) { if (g_ppc_current_pc == g_ppc_watch[__w].pc) { g_ppc_watch[__w].r3 = ctx->r[3]; g_ppc_watch[__w].r4 = ctx->r[4]; g_ppc_watch[__w].r5 = ctx->r[5]; g_ppc_watch[__w].r6 = ctx->r[6]; g_ppc_watch[__w].hit_count++; g_ppc_watch[__w].last_hit_call_count = g_ppc_fn_call_count; } }
  /* 0: stwu r1, -0x10(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)-16, ctx->r[1]);
  ctx->r[1] = ctx->r[1] + (int32_t)-16;
  /* 4: stw r31, 0xc(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)12, ctx->r[31]);
  /* 8: mr r31, r1 */
  ctx->r[31] = ctx->r[1];
  /* c: andi. r3, r3, 0x1f */
  ctx->r[3] = ctx->r[3] & 31u;
  ppc_cmpw(ctx, (int32_t)ctx->r[3], 0);
  /* 10: beq 0x8c */
  if (ctx->cr0_eq) goto L_8c;
  /* 14: cmpwi r5, 1 */
  ppc_cmpw(ctx, (int32_t)ctx->r[5], 1);
  /* 18: blt 0x94 */
  if (ctx->cr0_lt) goto L_94;
  /* 1c: li r6, 0 */
  ctx->r[6] = (uint32_t)(int32_t)0;
  /* 20: li r7, 0 */
  ctx->r[7] = (uint32_t)(int32_t)0;
  /* 24: beq 0x68 */
  if (ctx->cr0_eq) goto L_68;
  /* 28: rlwinm r6, r5, 0, 1, 0x1e */
  ctx->r[6] = ctx->r[5] & 2147483646u;
  /* 2c: addi r9, r6, -2 */
  ctx->r[9] = ctx->r[6] + (uint32_t)(int32_t)-2;
  /* 30: srwi r9, r9, 1 */
  ctx->r[9] = ctx->r[9] >> 1;
  /* 34: addi r9, r9, 1 */
  ctx->r[9] = ctx->r[9] + (uint32_t)(int32_t)1;
  /* 38: addi r7, r4, -8 */
  ctx->r[7] = ctx->r[4] + (uint32_t)(int32_t)-8;
  /* 3c: li r8, 0 */
  ctx->r[8] = (uint32_t)(int32_t)0;
  /* 40: mtctr r9 */
  ctx->ctr = ctx->r[9];
  /* 44: li r9, 0 */
  ctx->r[9] = (uint32_t)(int32_t)0;
  L_48: ;
  /* 48: lwzu r10, 8(r7) */
  ctx->r[10] = ppc_load_u32(ctx, ctx->r[7] + (int32_t)8);
  ctx->r[7] = ctx->r[7] + (int32_t)8;
  /* 4c: lwz r11, 4(r7) */
  ctx->r[11] = ppc_load_u32(ctx, ctx->r[7] + (int32_t)4);
  /* 50: add r8, r10, r8 */
  ctx->r[8] = ctx->r[10] + ctx->r[8];
  /* 54: add r9, r11, r9 */
  ctx->r[9] = ctx->r[11] + ctx->r[9];
  /* 58: bdnz 0x48 */
  if (--ctx->ctr != 0) goto L_48;
  /* 5c: cmplw r5, r6 */
  ppc_cmplw(ctx, ctx->r[5], ctx->r[6]);
  /* 60: add r7, r9, r8 */
  ctx->r[7] = ctx->r[9] + ctx->r[8];
  /* 64: beq 0x98 */
  if (ctx->cr0_eq) goto L_98;
  L_68: ;
  /* 68: slwi r8, r6, 2 */
  ctx->r[8] = ctx->r[6] << 2;
  /* 6c: add r4, r8, r4 */
  ctx->r[4] = ctx->r[8] + ctx->r[4];
  /* 70: subf r5, r6, r5 */
  ctx->r[5] = ctx->r[5] - ctx->r[6];
  /* 74: addi r4, r4, -4 */
  ctx->r[4] = ctx->r[4] + (uint32_t)(int32_t)-4;
  /* 78: mtctr r5 */
  ctx->ctr = ctx->r[5];
  L_7c: ;
  /* 7c: lwzu r5, 4(r4) */
  ctx->r[5] = ppc_load_u32(ctx, ctx->r[4] + (int32_t)4);
  ctx->r[4] = ctx->r[4] + (int32_t)4;
  /* 80: add r7, r5, r7 */
  ctx->r[7] = ctx->r[5] + ctx->r[7];
  /* 84: bdnz 0x7c */
  if (--ctx->ctr != 0) goto L_7c;
  /* 88: b 0x98 */
  goto L_98;
  L_8c: ;
  /* 8c: li r3, -1 */
  ctx->r[3] = (uint32_t)(int32_t)-1;
  /* 90: b 0x9c */
  goto L_9c;
  L_94: ;
  /* 94: li r7, 0 */
  ctx->r[7] = (uint32_t)(int32_t)0;
  L_98: ;
  /* 98: add r3, r7, r3 */
  ctx->r[3] = ctx->r[7] + ctx->r[3];
  L_9c: ;
  /* 9c: lwz r31, 0xc(r1) */
  ctx->r[31] = ppc_load_u32(ctx, ctx->r[1] + (int32_t)12);
  /* a0: addi r1, r1, 0x10 */
  ctx->r[1] = ctx->r[1] + (uint32_t)(int32_t)16;
  /* a4: blr  */
  return;
}
