/* Generated by Arkchemy's recomp tool. Do not edit by hand. */
#include "ppc_runtime.h"

void t12_carry_compute(PpcContext *ctx);
void t12_carry_dispatch(PpcContext *ctx, uint32_t addr);

void t12_carry_init_globals(PpcContext *ctx) {
}

void t12_carry_run_static_initializers(PpcContext *ctx) {
}

void t12_carry_dispatch(PpcContext *ctx, uint32_t addr) {
  switch (addr) {
    case 0u: t12_carry_compute(ctx); return;
  }
}

void t12_carry_compute(PpcContext *ctx) {
  g_ppc_last_caller_lr = ctx->lr;
  g_ppc_current_pc = 0x0u; g_ppc_fn_call_count++;
  for (int __w = 0; __w < ARKCHEMY_WATCH_SLOTS; __w++) { if (g_ppc_current_pc == g_ppc_watch[__w].pc) { g_ppc_watch[__w].r3 = ctx->r[3]; g_ppc_watch[__w].r4 = ctx->r[4]; g_ppc_watch[__w].r5 = ctx->r[5]; g_ppc_watch[__w].r6 = ctx->r[6]; g_ppc_watch[__w].hit_count++; g_ppc_watch[__w].last_hit_call_count = g_ppc_fn_call_count; } }
  /* 0: stwu r1, -0x50(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)-80, ctx->r[1]);
  ctx->r[1] = ctx->r[1] + (int32_t)-80;
  /* 4: stw r31, 0x4c(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)76, ctx->r[31]);
  /* 8: mr r31, r1 */
  ctx->r[31] = ctx->r[1];
  /* c: stw r3, 0x48(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)72, ctx->r[3]);
  /* 10: stw r4, 0x44(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)68, ctx->r[4]);
  /* 14: lwz r3, 0x48(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)72);
  /* 18: lwz r4, 0x44(r31) */
  ctx->r[4] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)68);
  /* 1c: stw r4, 0x3c(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)60, ctx->r[4]);
  /* 20: stw r3, 0x38(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)56, ctx->r[3]);
  /* 24: lis r3, -0x6544 */
  ctx->r[3] = 39612u << 16;
  /* 28: ori r3, r3, 0xdef0 */
  ctx->r[3] = ctx->r[3] | 57072u;
  /* 2c: stw r3, 0x34(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)52, ctx->r[3]);
  /* 30: lis r3, 0x1234 */
  ctx->r[3] = 4660u << 16;
  /* 34: ori r3, r3, 0x5678 */
  ctx->r[3] = ctx->r[3] | 22136u;
  /* 38: stw r3, 0x30(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)48, ctx->r[3]);
  /* 3c: lwz r3, 0x38(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)56);
  /* 40: lwz r4, 0x3c(r31) */
  ctx->r[4] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)60);
  /* 44: lwz r5, 0x30(r31) */
  ctx->r[5] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)48);
  /* 48: lwz r6, 0x34(r31) */
  ctx->r[6] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)52);
  /* 4c: addc r4, r4, r6 */
  ctx->r[4] = ppc_addc(ctx, ctx->r[4], ctx->r[6]);
  /* 50: adde r3, r3, r5 */
  ctx->r[3] = ppc_adde(ctx, ctx->r[3], ctx->r[5]);
  /* 54: stw r4, 0x2c(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)44, ctx->r[4]);
  /* 58: stw r3, 0x28(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)40, ctx->r[3]);
  /* 5c: li r3, 5 */
  ctx->r[3] = (uint32_t)(int32_t)5;
  /* 60: stw r3, 0x24(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)36, ctx->r[3]);
  /* 64: li r3, 0xa */
  ctx->r[3] = (uint32_t)(int32_t)10;
  /* 68: stw r3, 0x20(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)32, ctx->r[3]);
  /* 6c: lwz r3, 0x24(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)36);
  /* 70: lwz r4, 0x20(r31) */
  ctx->r[4] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)32);
  /* 74: cmplw r3, r4 */
  ppc_cmplw(ctx, ctx->r[3], ctx->r[4]);
  /* 78: li r3, 0 */
  ctx->r[3] = (uint32_t)(int32_t)0;
  /* 7c: stw r3, 0x14(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)20, ctx->r[3]);
  /* 80: li r3, 1 */
  ctx->r[3] = (uint32_t)(int32_t)1;
  /* 84: stw r3, 0x18(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)24, ctx->r[3]);
  /* 88: blt 0x94 */
  if (ctx->cr0_lt) goto L_94;
  /* 8c: lwz r3, 0x14(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)20);
  /* 90: stw r3, 0x18(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)24, ctx->r[3]);
  L_94: ;
  /* 94: lwz r3, 0x18(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)24);
  /* 98: stw r3, 0x1c(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)28, ctx->r[3]);
  /* 9c: lwz r3, 0x28(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)40);
  /* a0: lwz r4, 0x2c(r31) */
  ctx->r[4] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)44);
  /* a4: lwz r6, 0x1c(r31) */
  ctx->r[6] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)28);
  /* a8: srawi r5, r6, 0x1f */
  ctx->r[5] = (uint32_t)((int32_t)ctx->r[6] >> 31);
  /* ac: addc r4, r4, r6 */
  ctx->r[4] = ppc_addc(ctx, ctx->r[4], ctx->r[6]);
  /* b0: adde r3, r3, r5 */
  ctx->r[3] = ppc_adde(ctx, ctx->r[3], ctx->r[5]);
  /* b4: lwz r31, 0x4c(r1) */
  ctx->r[31] = ppc_load_u32(ctx, ctx->r[1] + (int32_t)76);
  /* b8: addi r1, r1, 0x50 */
  ctx->r[1] = ctx->r[1] + (uint32_t)(int32_t)80;
  /* bc: blr  */
  return;
}
