/* Generated by Arkchemy's recomp tool. Do not edit by hand. */
#include "ppc_runtime.h"

void t21_multifunc_globals_bump(PpcContext *ctx);
void t21_multifunc_globals_read_shared(PpcContext *ctx);
void t21_multifunc_globals_compute(PpcContext *ctx);
void t21_multifunc_globals_dispatch(PpcContext *ctx, uint32_t addr);

void t21_multifunc_globals_init_globals(PpcContext *ctx) {
  ppc_store_u8(ctx, 8195u, 5);
}

void t21_multifunc_globals_run_static_initializers(PpcContext *ctx) {
}

void t21_multifunc_globals_dispatch(PpcContext *ctx, uint32_t addr) {
  switch (addr) {
    case 0u: t21_multifunc_globals_bump(ctx); return;
    case 48u: t21_multifunc_globals_read_shared(ctx); return;
    case 80u: t21_multifunc_globals_compute(ctx); return;
  }
}

void t21_multifunc_globals_bump(PpcContext *ctx) {
  g_ppc_last_caller_lr = ctx->lr;
  g_ppc_current_pc = 0x0u; g_ppc_fn_call_count++;
  for (int __w = 0; __w < ARKCHEMY_WATCH_SLOTS; __w++) { if (g_ppc_current_pc == g_ppc_watch[__w].pc) { g_ppc_watch[__w].r3 = ctx->r[3]; g_ppc_watch[__w].r4 = ctx->r[4]; g_ppc_watch[__w].r5 = ctx->r[5]; g_ppc_watch[__w].r6 = ctx->r[6]; g_ppc_watch[__w].hit_count++; g_ppc_watch[__w].last_hit_call_count = g_ppc_fn_call_count; } }
  /* 0: stwu r1, -0x10(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)-16, ctx->r[1]);
  ctx->r[1] = ctx->r[1] + (int32_t)-16;
  /* 4: stw r31, 0xc(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)12, ctx->r[31]);
  /* 8: mr r31, r1 */
  ctx->r[31] = ctx->r[1];
  /* c: stw r3, 8(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)8, ctx->r[3]);
  /* 10: lwz r5, 8(r31) */
  ctx->r[5] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)8);
  /* 14: lis r4, 0 */
  ctx->r[4] = 8192u; /* &.data+0 */
  /* 18: lwz r3, 0(r4) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[4]);
  /* 1c: add r3, r3, r5 */
  ctx->r[3] = ctx->r[3] + ctx->r[5];
  /* 20: stw r3, 0(r4) */
  ppc_store_u32(ctx, ctx->r[4], ctx->r[3]);
  /* 24: lwz r31, 0xc(r1) */
  ctx->r[31] = ppc_load_u32(ctx, ctx->r[1] + (int32_t)12);
  /* 28: addi r1, r1, 0x10 */
  ctx->r[1] = ctx->r[1] + (uint32_t)(int32_t)16;
  /* 2c: blr  */
  return;
}
void t21_multifunc_globals_read_shared(PpcContext *ctx) {
  g_ppc_last_caller_lr = ctx->lr;
  g_ppc_current_pc = 0x30u; g_ppc_fn_call_count++;
  for (int __w = 0; __w < ARKCHEMY_WATCH_SLOTS; __w++) { if (g_ppc_current_pc == g_ppc_watch[__w].pc) { g_ppc_watch[__w].r3 = ctx->r[3]; g_ppc_watch[__w].r4 = ctx->r[4]; g_ppc_watch[__w].r5 = ctx->r[5]; g_ppc_watch[__w].r6 = ctx->r[6]; g_ppc_watch[__w].hit_count++; g_ppc_watch[__w].last_hit_call_count = g_ppc_fn_call_count; } }
  /* 30: stwu r1, -0x10(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)-16, ctx->r[1]);
  ctx->r[1] = ctx->r[1] + (int32_t)-16;
  /* 34: stw r31, 0xc(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)12, ctx->r[31]);
  /* 38: mr r31, r1 */
  ctx->r[31] = ctx->r[1];
  /* 3c: lis r3, 0 */
  ctx->r[3] = 8192u; /* &.data+0 */
  /* 40: lwz r3, 0(r3) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[3]);
  /* 44: lwz r31, 0xc(r1) */
  ctx->r[31] = ppc_load_u32(ctx, ctx->r[1] + (int32_t)12);
  /* 48: addi r1, r1, 0x10 */
  ctx->r[1] = ctx->r[1] + (uint32_t)(int32_t)16;
  /* 4c: blr  */
  return;
}
void t21_multifunc_globals_compute(PpcContext *ctx) {
  g_ppc_last_caller_lr = ctx->lr;
  g_ppc_current_pc = 0x50u; g_ppc_fn_call_count++;
  for (int __w = 0; __w < ARKCHEMY_WATCH_SLOTS; __w++) { if (g_ppc_current_pc == g_ppc_watch[__w].pc) { g_ppc_watch[__w].r3 = ctx->r[3]; g_ppc_watch[__w].r4 = ctx->r[4]; g_ppc_watch[__w].r5 = ctx->r[5]; g_ppc_watch[__w].r6 = ctx->r[6]; g_ppc_watch[__w].hit_count++; g_ppc_watch[__w].last_hit_call_count = g_ppc_fn_call_count; } }
  /* 50: mflr r0 */
  ctx->r[0] = ctx->lr;
  /* 54: stwu r1, -0x20(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)-32, ctx->r[1]);
  ctx->r[1] = ctx->r[1] + (int32_t)-32;
  /* 58: stw r31, 0x1c(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)28, ctx->r[31]);
  /* 5c: stw r0, 0x24(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)36, ctx->r[0]);
  /* 60: mr r31, r1 */
  ctx->r[31] = ctx->r[1];
  /* 64: stw r3, 0x18(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)24, ctx->r[3]);
  /* 68: stw r4, 0x14(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)20, ctx->r[4]);
  /* 6c: lwz r3, 0x18(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)24);
  /* 70: bl 0x70 */
  ctx->lr = 0x74u;
  t21_multifunc_globals_bump(ctx);
  /* 74: lwz r3, 0x14(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)20);
  /* 78: bl 0x78 */
  ctx->lr = 0x7cu;
  t21_multifunc_globals_bump(ctx);
  /* 7c: bl 0x7c */
  ctx->lr = 0x80u;
  t21_multifunc_globals_read_shared(ctx);
  /* 80: lwz r0, 0x24(r1) */
  ctx->r[0] = ppc_load_u32(ctx, ctx->r[1] + (int32_t)36);
  /* 84: lwz r31, 0x1c(r1) */
  ctx->r[31] = ppc_load_u32(ctx, ctx->r[1] + (int32_t)28);
  /* 88: addi r1, r1, 0x20 */
  ctx->r[1] = ctx->r[1] + (uint32_t)(int32_t)32;
  /* 8c: mtlr r0 */
  ctx->lr = ctx->r[0];
  /* 90: blr  */
  return;
}
