/* Generated by Arkchemy's recomp tool. Do not edit by hand. */
#include "ppc_runtime.h"

void t2_floating_compute(PpcContext *ctx);
void t2_floating_dispatch(PpcContext *ctx, uint32_t addr);

void t2_floating_init_globals(PpcContext *ctx) {
  ppc_store_u8(ctx, 8192u, 63);
}

void t2_floating_dispatch(PpcContext *ctx, uint32_t addr) {
  switch (addr) {
    case 0u: t2_floating_compute(ctx); return;
  }
}

void t2_floating_compute(PpcContext *ctx) {
  /* 0: stwu r1, -0x20(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)-32, ctx->r[1]);
  ctx->r[1] = ctx->r[1] + (int32_t)-32;
  /* 4: stw r31, 0x1c(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)28, ctx->r[31]);
  /* 8: mr r31, r1 */
  ctx->r[31] = ctx->r[1];
  /* c: lis r3, 0x3fc0 */
  ctx->r[3] = 16320u << 16;
  /* 10: stw r3, 0x18(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)24, ctx->r[3]);
  /* 14: lis r3, 0x4010 */
  ctx->r[3] = 16400u << 16;
  /* 18: stw r3, 0x14(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)20, ctx->r[3]);
  /* 1c: li r3, 0 */
  ctx->r[3] = (uint32_t)(int32_t)0;
  /* 20: stw r3, 0x10(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)16, ctx->r[3]);
  /* 24: stw r3, 0xc(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)12, ctx->r[3]);
  /* 28: b 0x2c */
  goto L_2c;
  L_2c: ;
  /* 2c: lwz r3, 0xc(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)12);
  /* 30: cmpwi r3, 3 */
  ppc_cmpw(ctx, (int32_t)ctx->r[3], 3);
  /* 34: bgt 0x78 */
  if (ctx->cr0_gt) goto L_78;
  /* 38: b 0x3c */
  goto L_3c;
  L_3c: ;
  /* 3c: lfs f2, 0x10(r31) */
  ctx->f[2] = (double)ppc_load_f32(ctx, ctx->r[31] + (int32_t)16);
  /* 40: lfs f0, 0x18(r31) */
  ctx->f[0] = (double)ppc_load_f32(ctx, ctx->r[31] + (int32_t)24);
  /* 44: lfs f1, 0x14(r31) */
  ctx->f[1] = (double)ppc_load_f32(ctx, ctx->r[31] + (int32_t)20);
  /* 48: fmadds f0, f0, f1, f2 */
  ctx->f[0] = ppc_frsp(ctx->f[0] * ctx->f[1] + ctx->f[2]);
  /* 4c: stfs f0, 0x10(r31) */
  ppc_store_f32(ctx, ctx->r[31] + (int32_t)16, ctx->f[0]);
  /* 50: lfs f0, 0x18(r31) */
  ctx->f[0] = (double)ppc_load_f32(ctx, ctx->r[31] + (int32_t)24);
  /* 54: lis r3, 0 */
  ctx->r[3] = 8192u; /* &.rodata.cst4+0 */
  /* 58: lfs f1, 0(r3) */
  ctx->f[1] = (double)ppc_load_f32(ctx, ctx->r[3]);
  /* 5c: fadds f0, f0, f1 */
  ctx->f[0] = ppc_frsp(ctx->f[0] + ctx->f[1]);
  /* 60: stfs f0, 0x18(r31) */
  ppc_store_f32(ctx, ctx->r[31] + (int32_t)24, ctx->f[0]);
  /* 64: b 0x68 */
  goto L_68;
  L_68: ;
  /* 68: lwz r3, 0xc(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)12);
  /* 6c: addi r3, r3, 1 */
  ctx->r[3] = ctx->r[3] + (uint32_t)(int32_t)1;
  /* 70: stw r3, 0xc(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)12, ctx->r[3]);
  /* 74: b 0x2c */
  goto L_2c;
  L_78: ;
  /* 78: lfs f1, 0x10(r31) */
  ctx->f[1] = (double)ppc_load_f32(ctx, ctx->r[31] + (int32_t)16);
  /* 7c: lwz r31, 0x1c(r1) */
  ctx->r[31] = ppc_load_u32(ctx, ctx->r[1] + (int32_t)28);
  /* 80: addi r1, r1, 0x20 */
  ctx->r[1] = ctx->r[1] + (uint32_t)(int32_t)32;
  /* 84: blr  */
  return;
}
