/* Generated by Arkchemy's recomp tool. Do not edit by hand. */
#include "ppc_runtime.h"

void t5_fnptr_add(PpcContext *ctx);
void t5_fnptr_mul(PpcContext *ctx);
void t5_fnptr_compute(PpcContext *ctx);
void t5_fnptr_dispatch(PpcContext *ctx, uint32_t addr);

void t5_fnptr_init_globals(PpcContext *ctx) {
}

void t5_fnptr_dispatch(PpcContext *ctx, uint32_t addr) {
  switch (addr) {
    case 0u: t5_fnptr_add(ctx); return;
    case 44u: t5_fnptr_mul(ctx); return;
    case 88u: t5_fnptr_compute(ctx); return;
  }
}

void t5_fnptr_add(PpcContext *ctx) {
  /* 0: stwu r1, -0x20(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)-32, ctx->r[1]);
  ctx->r[1] = ctx->r[1] + (int32_t)-32;
  /* 4: stw r31, 0x1c(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)28, ctx->r[31]);
  /* 8: mr r31, r1 */
  ctx->r[31] = ctx->r[1];
  /* c: stw r3, 0x18(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)24, ctx->r[3]);
  /* 10: stw r4, 0x14(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)20, ctx->r[4]);
  /* 14: lwz r3, 0x18(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)24);
  /* 18: lwz r4, 0x14(r31) */
  ctx->r[4] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)20);
  /* 1c: add r3, r3, r4 */
  ctx->r[3] = ctx->r[3] + ctx->r[4];
  /* 20: lwz r31, 0x1c(r1) */
  ctx->r[31] = ppc_load_u32(ctx, ctx->r[1] + (int32_t)28);
  /* 24: addi r1, r1, 0x20 */
  ctx->r[1] = ctx->r[1] + (uint32_t)(int32_t)32;
  /* 28: blr  */
  return;
}
void t5_fnptr_mul(PpcContext *ctx) {
  /* 2c: stwu r1, -0x20(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)-32, ctx->r[1]);
  ctx->r[1] = ctx->r[1] + (int32_t)-32;
  /* 30: stw r31, 0x1c(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)28, ctx->r[31]);
  /* 34: mr r31, r1 */
  ctx->r[31] = ctx->r[1];
  /* 38: stw r3, 0x18(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)24, ctx->r[3]);
  /* 3c: stw r4, 0x14(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)20, ctx->r[4]);
  /* 40: lwz r3, 0x18(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)24);
  /* 44: lwz r4, 0x14(r31) */
  ctx->r[4] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)20);
  /* 48: mullw r3, r3, r4 */
  ctx->r[3] = ctx->r[3] * ctx->r[4];
  /* 4c: lwz r31, 0x1c(r1) */
  ctx->r[31] = ppc_load_u32(ctx, ctx->r[1] + (int32_t)28);
  /* 50: addi r1, r1, 0x20 */
  ctx->r[1] = ctx->r[1] + (uint32_t)(int32_t)32;
  /* 54: blr  */
  return;
}
void t5_fnptr_compute(PpcContext *ctx) {
  /* 58: mflr r0 */
  ctx->r[0] = ctx->lr;
  /* 5c: stwu r1, -0x20(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)-32, ctx->r[1]);
  ctx->r[1] = ctx->r[1] + (int32_t)-32;
  /* 60: stw r31, 0x1c(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)28, ctx->r[31]);
  /* 64: stw r0, 0x24(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)36, ctx->r[0]);
  /* 68: mr r31, r1 */
  ctx->r[31] = ctx->r[1];
  /* 6c: stw r3, 0x18(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)24, ctx->r[3]);
  /* 70: stw r4, 0x14(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)20, ctx->r[4]);
  /* 74: stw r5, 0x10(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)16, ctx->r[5]);
  /* 78: lwz r5, 0x10(r31) */
  ctx->r[5] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)16);
  /* 7c: lis r3, 0 */
  ctx->r[3] = 0u; /* &add */
  /* 80: addi r3, r3, 0 */
  ctx->r[3] = ctx->r[3];
  /* 84: lis r4, 0 */
  ctx->r[4] = 44u; /* &mul */
  /* 88: addi r4, r4, 0 */
  ctx->r[4] = ctx->r[4];
  /* 8c: cmplwi r5, 0 */
  ppc_cmplw(ctx, ctx->r[5], 0u);
  /* 90: beq 0x9c */
  if (ctx->cr0_eq) goto L_9c;
  /* 94: ori r3, r4, 0 */
  ctx->r[3] = ctx->r[4] | 0u;
  /* 98: b 0x9c */
  goto L_9c;
  L_9c: ;
  /* 9c: stw r3, 0xc(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)12, ctx->r[3]);
  /* a0: lwz r5, 0xc(r31) */
  ctx->r[5] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)12);
  /* a4: lwz r3, 0x18(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)24);
  /* a8: lwz r4, 0x14(r31) */
  ctx->r[4] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)20);
  /* ac: mtctr r5 */
  ctx->ctr = ctx->r[5];
  /* b0: bctrl  */
  t5_fnptr_dispatch(ctx, ctx->ctr);
  /* b4: lwz r0, 0x24(r1) */
  ctx->r[0] = ppc_load_u32(ctx, ctx->r[1] + (int32_t)36);
  /* b8: lwz r31, 0x1c(r1) */
  ctx->r[31] = ppc_load_u32(ctx, ctx->r[1] + (int32_t)28);
  /* bc: addi r1, r1, 0x20 */
  ctx->r[1] = ctx->r[1] + (uint32_t)(int32_t)32;
  /* c0: mtlr r0 */
  ctx->lr = ctx->r[0];
  /* c4: blr  */
  return;
}
