/* Generated by Arkchemy's recomp tool. Do not edit by hand. */
#include "ppc_runtime.h"

void t14_indexed_compute(PpcContext *ctx);
void t14_indexed_dispatch(PpcContext *ctx, uint32_t addr);

void t14_indexed_init_globals(PpcContext *ctx) {
}

void t14_indexed_run_static_initializers(PpcContext *ctx) {
}

void t14_indexed_dispatch(PpcContext *ctx, uint32_t addr) {
  switch (addr) {
    case 0u: t14_indexed_compute(ctx); return;
  }
}

void t14_indexed_compute(PpcContext *ctx) {
  g_ppc_last_caller_lr = ctx->lr;
  g_ppc_current_pc = 0x0u; g_ppc_fn_call_count++;
  for (int __w = 0; __w < ARKCHEMY_WATCH_SLOTS; __w++) { if (g_ppc_current_pc == g_ppc_watch[__w].pc) { g_ppc_watch[__w].r3 = ctx->r[3]; g_ppc_watch[__w].r4 = ctx->r[4]; g_ppc_watch[__w].r5 = ctx->r[5]; g_ppc_watch[__w].r6 = ctx->r[6]; g_ppc_watch[__w].hit_count++; g_ppc_watch[__w].last_hit_call_count = g_ppc_fn_call_count; } }
  /* 0: stwu r1, -0x30(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)-48, ctx->r[1]);
  ctx->r[1] = ctx->r[1] + (int32_t)-48;
  /* 4: stw r31, 0x2c(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)44, ctx->r[31]);
  /* 8: mr r31, r1 */
  ctx->r[31] = ctx->r[1];
  /* c: stw r3, 0x28(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)40, ctx->r[3]);
  /* 10: stw r4, 0x24(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)36, ctx->r[4]);
  /* 14: li r3, 0 */
  ctx->r[3] = (uint32_t)(int32_t)0;
  /* 18: stw r3, 0x20(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)32, ctx->r[3]);
  /* 1c: stw r3, 0x1c(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)28, ctx->r[3]);
  /* 20: b 0x24 */
  goto L_24;
  L_24: ;
  /* 24: lwz r3, 0x1c(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)28);
  /* 28: lwz r4, 0x24(r31) */
  ctx->r[4] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)36);
  /* 2c: cmpw r3, r4 */
  ppc_cmpw(ctx, (int32_t)ctx->r[3], (int32_t)ctx->r[4]);
  /* 30: bge 0x68 */
  if ((ctx->cr0_gt || ctx->cr0_eq)) goto L_68;
  /* 34: b 0x38 */
  goto L_38;
  L_38: ;
  /* 38: lwz r3, 0x28(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)40);
  /* 3c: lwz r4, 0x1c(r31) */
  ctx->r[4] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)28);
  /* 40: slwi r4, r4, 2 */
  ctx->r[4] = ctx->r[4] << 2;
  /* 44: lwzx r4, r3, r4 */
  ctx->r[4] = ppc_load_u32(ctx, ctx->r[3] + ctx->r[4]);
  /* 48: lwz r3, 0x20(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)32);
  /* 4c: add r3, r3, r4 */
  ctx->r[3] = ctx->r[3] + ctx->r[4];
  /* 50: stw r3, 0x20(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)32, ctx->r[3]);
  /* 54: b 0x58 */
  goto L_58;
  L_58: ;
  /* 58: lwz r3, 0x1c(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)28);
  /* 5c: addi r3, r3, 1 */
  ctx->r[3] = ctx->r[3] + (uint32_t)(int32_t)1;
  /* 60: stw r3, 0x1c(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)28, ctx->r[3]);
  /* 64: b 0x24 */
  goto L_24;
  L_68: ;
  /* 68: lwz r3, 0x24(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)36);
  /* 6c: stw r3, 0x18(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)24, ctx->r[3]);
  /* 70: lwz r3, 0x18(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)24);
  /* 74: cmplwi r3, 0x63 */
  ppc_cmplw(ctx, ctx->r[3], 99u);
  /* 78: li r3, 0 */
  ctx->r[3] = (uint32_t)(int32_t)0;
  /* 7c: stw r3, 0xc(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)12, ctx->r[3]);
  /* 80: li r3, 1 */
  ctx->r[3] = (uint32_t)(int32_t)1;
  /* 84: stw r3, 0x10(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)16, ctx->r[3]);
  /* 88: bgt 0x94 */
  if (ctx->cr0_gt) goto L_94;
  /* 8c: lwz r3, 0xc(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)12);
  /* 90: stw r3, 0x10(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)16, ctx->r[3]);
  L_94: ;
  /* 94: lwz r3, 0x10(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)16);
  /* 98: stw r3, 0x14(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)20, ctx->r[3]);
  /* 9c: lwz r3, 0x20(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)32);
  /* a0: lwz r4, 0x14(r31) */
  ctx->r[4] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)20);
  /* a4: add r3, r3, r4 */
  ctx->r[3] = ctx->r[3] + ctx->r[4];
  /* a8: lwz r31, 0x2c(r1) */
  ctx->r[31] = ppc_load_u32(ctx, ctx->r[1] + (int32_t)44);
  /* ac: addi r1, r1, 0x30 */
  ctx->r[1] = ctx->r[1] + (uint32_t)(int32_t)48;
  /* b0: blr  */
  return;
}
