/* Generated by Arkchemy's recomp tool. Do not edit by hand. */
#include "ppc_runtime.h"

void t23_multifile_helper(PpcContext *ctx);
void t23_multifile_a_dispatch(PpcContext *ctx, uint32_t addr);

/* --extern-globals: t23_multifile_a_init_globals/t23_multifile_a_dispatch are defined in the primary translation unit, not here. */

void t23_multifile_helper(PpcContext *ctx) {
  g_ppc_last_caller_lr = ctx->lr;
  g_ppc_current_pc = 0x0u; g_ppc_fn_call_count++;
  for (int __w = 0; __w < ARKCHEMY_WATCH_SLOTS; __w++) { if (g_ppc_current_pc == g_ppc_watch[__w].pc) { g_ppc_watch[__w].r3 = ctx->r[3]; g_ppc_watch[__w].r4 = ctx->r[4]; g_ppc_watch[__w].r5 = ctx->r[5]; g_ppc_watch[__w].r6 = ctx->r[6]; g_ppc_watch[__w].hit_count++; g_ppc_watch[__w].last_hit_call_count = g_ppc_fn_call_count; } }
  /* 0: stwu r1, -0x10(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)-16, ctx->r[1]);
  ctx->r[1] = ctx->r[1] + (int32_t)-16;
  /* 4: stw r31, 0xc(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)12, ctx->r[31]);
  /* 8: mr r31, r1 */
  ctx->r[31] = ctx->r[1];
  /* c: stw r3, 8(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)8, ctx->r[3]);
  /* 10: lwz r3, 8(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)8);
  /* 14: mulli r3, r3, 3 */
  ctx->r[3] = ctx->r[3] * (uint32_t)(int32_t)3;
  /* 18: addi r3, r3, 1 */
  ctx->r[3] = ctx->r[3] + (uint32_t)(int32_t)1;
  /* 1c: lwz r31, 0xc(r1) */
  ctx->r[31] = ppc_load_u32(ctx, ctx->r[1] + (int32_t)12);
  /* 20: addi r1, r1, 0x10 */
  ctx->r[1] = ctx->r[1] + (uint32_t)(int32_t)16;
  /* 24: blr  */
  return;
}
