/* Generated by Arkchemy's recomp tool. Do not edit by hand. */
#include "ppc_runtime.h"

void t16_mulhw_compute(PpcContext *ctx);
void t16_mulhw_dispatch(PpcContext *ctx, uint32_t addr);

void t16_mulhw_init_globals(PpcContext *ctx) {
}

void t16_mulhw_run_static_initializers(PpcContext *ctx) {
}

void t16_mulhw_dispatch(PpcContext *ctx, uint32_t addr) {
  switch (addr) {
    case 0u: t16_mulhw_compute(ctx); return;
  }
}

void t16_mulhw_compute(PpcContext *ctx) {
  g_ppc_last_caller_lr = ctx->lr;
  g_ppc_current_pc = 0x0u; g_ppc_fn_call_count++;
  for (int __w = 0; __w < ARKCHEMY_WATCH_SLOTS; __w++) { if (g_ppc_current_pc == g_ppc_watch[__w].pc) { g_ppc_watch[__w].r3 = ctx->r[3]; g_ppc_watch[__w].r4 = ctx->r[4]; g_ppc_watch[__w].r5 = ctx->r[5]; g_ppc_watch[__w].r6 = ctx->r[6]; g_ppc_watch[__w].hit_count++; g_ppc_watch[__w].last_hit_call_count = g_ppc_fn_call_count; } }
  /* 0: stwu r1, -0x10(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)-16, ctx->r[1]);
  ctx->r[1] = ctx->r[1] + (int32_t)-16;
  /* 4: stw r31, 0xc(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)12, ctx->r[31]);
  /* 8: mr r31, r1 */
  ctx->r[31] = ctx->r[1];
  /* c: lis r5, -0x6db7 */
  ctx->r[5] = 37449u << 16;
  /* 10: ori r5, r5, 0x2493 */
  ctx->r[5] = ctx->r[5] | 9363u;
  /* 14: mulhw r5, r3, r5 */
  ctx->r[5] = ppc_mulhw((int32_t)ctx->r[3], (int32_t)ctx->r[5]);
  /* 18: add r3, r5, r3 */
  ctx->r[3] = ctx->r[5] + ctx->r[3];
  /* 1c: srwi r5, r3, 0x1f */
  ctx->r[5] = ctx->r[3] >> 31;
  /* 20: srawi r3, r3, 2 */
  ctx->r[3] = (uint32_t)((int32_t)ctx->r[3] >> 2);
  /* 24: add r3, r3, r5 */
  ctx->r[3] = ctx->r[3] + ctx->r[5];
  /* 28: lis r5, 0x2492 */
  ctx->r[5] = 9362u << 16;
  /* 2c: ori r5, r5, 0x4925 */
  ctx->r[5] = ctx->r[5] | 18725u;
  /* 30: mulhwu r5, r4, r5 */
  ctx->r[5] = ppc_mulhwu(ctx->r[4], ctx->r[5]);
  /* 34: subf r4, r5, r4 */
  ctx->r[4] = ctx->r[4] - ctx->r[5];
  /* 38: srwi r4, r4, 1 */
  ctx->r[4] = ctx->r[4] >> 1;
  /* 3c: add r4, r4, r5 */
  ctx->r[4] = ctx->r[4] + ctx->r[5];
  /* 40: srwi r4, r4, 2 */
  ctx->r[4] = ctx->r[4] >> 2;
  /* 44: add r3, r4, r3 */
  ctx->r[3] = ctx->r[4] + ctx->r[3];
  /* 48: lwz r31, 0xc(r1) */
  ctx->r[31] = ppc_load_u32(ctx, ctx->r[1] + (int32_t)12);
  /* 4c: addi r1, r1, 0x10 */
  ctx->r[1] = ctx->r[1] + (uint32_t)(int32_t)16;
  /* 50: blr  */
  return;
}
