/* Generated by Arkchemy's recomp tool. Do not edit by hand. */
#include "ppc_runtime.h"

void t3_loop_sumn(PpcContext *ctx);
void t3_loop_dispatch(PpcContext *ctx, uint32_t addr);

void t3_loop_init_globals(PpcContext *ctx) {
}

void t3_loop_dispatch(PpcContext *ctx, uint32_t addr) {
  switch (addr) {
    case 0u: t3_loop_sumn(ctx); return;
  }
}

void t3_loop_sumn(PpcContext *ctx) {
  /* 0: cmpwi r3, 0 */
  ppc_cmpw(ctx, (int32_t)ctx->r[3], 0);
  /* 4: ble 0x20 */
  if ((ctx->cr0_lt || ctx->cr0_eq)) goto L_20;
  /* 8: mtctr r3 */
  ctx->ctr = ctx->r[3];
  /* c: li r3, 0 */
  ctx->r[3] = (uint32_t)(int32_t)0;
  L_10: ;
  /* 10: lwz r5, 0(r4) */
  ctx->r[5] = ppc_load_u32(ctx, ctx->r[4] + (int32_t)0);
  /* 14: add r3, r5, r3 */
  ctx->r[3] = ctx->r[5] + ctx->r[3];
  /* 18: bdnz 0x10 */
  if (--ctx->ctr != 0) goto L_10;
  /* 1c: blr  */
  return;
  L_20: ;
  /* 20: li r3, 0 */
  ctx->r[3] = (uint32_t)(int32_t)0;
  /* 24: blr  */
  return;
}
