/* Generated by Arkchemy's recomp tool. Do not edit by hand. */
#include "ppc_runtime.h"

void t1_arithmetic_add(PpcContext *ctx);
void t1_arithmetic_compute(PpcContext *ctx);
void t1_arithmetic_dispatch(PpcContext *ctx, uint32_t addr);

void t1_arithmetic_init_globals(PpcContext *ctx) {
}

void t1_arithmetic_run_static_initializers(PpcContext *ctx) {
}

void t1_arithmetic_dispatch(PpcContext *ctx, uint32_t addr) {
  switch (addr) {
    case 0u: t1_arithmetic_add(ctx); return;
    case 44u: t1_arithmetic_compute(ctx); return;
  }
}

void t1_arithmetic_add(PpcContext *ctx) {
  g_ppc_last_caller_lr = ctx->lr;
  g_ppc_current_pc = 0x0u; g_ppc_fn_call_count++;
  for (int __w = 0; __w < ARKCHEMY_WATCH_SLOTS; __w++) { if (g_ppc_current_pc == g_ppc_watch[__w].pc) { g_ppc_watch[__w].r3 = ctx->r[3]; g_ppc_watch[__w].r4 = ctx->r[4]; g_ppc_watch[__w].r5 = ctx->r[5]; g_ppc_watch[__w].r6 = ctx->r[6]; g_ppc_watch[__w].hit_count++; g_ppc_watch[__w].last_hit_call_count = g_ppc_fn_call_count; } }
  /* 0: stwu r1, -0x20(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)-32, ctx->r[1]);
  ctx->r[1] = ctx->r[1] + (int32_t)-32;
  /* 4: stw r31, 0x1c(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)28, ctx->r[31]);
  /* 8: mr r31, r1 */
  ctx->r[31] = ctx->r[1];
  /* c: stw r3, 0x18(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)24, ctx->r[3]);
  /* 10: stw r4, 0x14(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)20, ctx->r[4]);
  /* 14: lwz r3, 0x18(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)24);
  /* 18: lwz r4, 0x14(r31) */
  ctx->r[4] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)20);
  /* 1c: add r3, r3, r4 */
  ctx->r[3] = ctx->r[3] + ctx->r[4];
  /* 20: lwz r31, 0x1c(r1) */
  ctx->r[31] = ppc_load_u32(ctx, ctx->r[1] + (int32_t)28);
  /* 24: addi r1, r1, 0x20 */
  ctx->r[1] = ctx->r[1] + (uint32_t)(int32_t)32;
  /* 28: blr  */
  return;
}
void t1_arithmetic_compute(PpcContext *ctx) {
  g_ppc_last_caller_lr = ctx->lr;
  g_ppc_current_pc = 0x2cu; g_ppc_fn_call_count++;
  for (int __w = 0; __w < ARKCHEMY_WATCH_SLOTS; __w++) { if (g_ppc_current_pc == g_ppc_watch[__w].pc) { g_ppc_watch[__w].r3 = ctx->r[3]; g_ppc_watch[__w].r4 = ctx->r[4]; g_ppc_watch[__w].r5 = ctx->r[5]; g_ppc_watch[__w].r6 = ctx->r[6]; g_ppc_watch[__w].hit_count++; g_ppc_watch[__w].last_hit_call_count = g_ppc_fn_call_count; } }
  /* 2c: mflr r0 */
  ctx->r[0] = ctx->lr;
  /* 30: stwu r1, -0x20(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)-32, ctx->r[1]);
  ctx->r[1] = ctx->r[1] + (int32_t)-32;
  /* 34: stw r31, 0x1c(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)28, ctx->r[31]);
  /* 38: stw r0, 0x24(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)36, ctx->r[0]);
  /* 3c: mr r31, r1 */
  ctx->r[31] = ctx->r[1];
  /* 40: li r3, 0 */
  ctx->r[3] = (uint32_t)(int32_t)0;
  /* 44: stw r3, 0x18(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)24, ctx->r[3]);
  /* 48: li r4, 1 */
  ctx->r[4] = (uint32_t)(int32_t)1;
  /* 4c: stw r4, 0x14(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)20, ctx->r[4]);
  /* 50: stw r3, 0x10(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)16, ctx->r[3]);
  /* 54: b 0x58 */
  goto L_58;
  L_58: ;
  /* 58: lwz r3, 0x10(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)16);
  /* 5c: cmpwi r3, 9 */
  ppc_cmpw(ctx, (int32_t)ctx->r[3], 9);
  /* 60: bgt 0x9c */
  if (ctx->cr0_gt) goto L_9c;
  /* 64: b 0x68 */
  goto L_68;
  L_68: ;
  /* 68: lwz r3, 0x18(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)24);
  /* 6c: lwz r4, 0x14(r31) */
  ctx->r[4] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)20);
  /* 70: bl 0x70 */
  ctx->lr = 0x74u;
  t1_arithmetic_add(ctx);
  /* 74: stw r3, 0xc(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)12, ctx->r[3]);
  /* 78: lwz r3, 0x14(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)20);
  /* 7c: stw r3, 0x18(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)24, ctx->r[3]);
  /* 80: lwz r3, 0xc(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)12);
  /* 84: stw r3, 0x14(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)20, ctx->r[3]);
  /* 88: b 0x8c */
  goto L_8c;
  L_8c: ;
  /* 8c: lwz r3, 0x10(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)16);
  /* 90: addi r3, r3, 1 */
  ctx->r[3] = ctx->r[3] + (uint32_t)(int32_t)1;
  /* 94: stw r3, 0x10(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)16, ctx->r[3]);
  /* 98: b 0x58 */
  goto L_58;
  L_9c: ;
  /* 9c: lwz r3, 0x14(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)20);
  /* a0: mulli r3, r3, 3 */
  ctx->r[3] = ctx->r[3] * (uint32_t)(int32_t)3;
  /* a4: addi r3, r3, -7 */
  ctx->r[3] = ctx->r[3] + (uint32_t)(int32_t)-7;
  /* a8: stw r3, 8(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)8, ctx->r[3]);
  /* ac: lwz r3, 8(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)8);
  /* b0: lwz r0, 0x24(r1) */
  ctx->r[0] = ppc_load_u32(ctx, ctx->r[1] + (int32_t)36);
  /* b4: lwz r31, 0x1c(r1) */
  ctx->r[31] = ppc_load_u32(ctx, ctx->r[1] + (int32_t)28);
  /* b8: addi r1, r1, 0x20 */
  ctx->r[1] = ctx->r[1] + (uint32_t)(int32_t)32;
  /* bc: mtlr r0 */
  ctx->lr = ctx->r[0];
  /* c0: blr  */
  return;
}
