/* Generated by Arkchemy's recomp tool. Do not edit by hand. */
#include "ppc_runtime.h"

void t10_bitops_compute(PpcContext *ctx);
void t10_bitops_dispatch(PpcContext *ctx, uint32_t addr);

void t10_bitops_init_globals(PpcContext *ctx) {
}

void t10_bitops_run_static_initializers(PpcContext *ctx) {
}

void t10_bitops_dispatch(PpcContext *ctx, uint32_t addr) {
  switch (addr) {
    case 0u: t10_bitops_compute(ctx); return;
  }
}

void t10_bitops_compute(PpcContext *ctx) {
  g_ppc_last_caller_lr = ctx->lr;
  g_ppc_current_pc = 0x0u; g_ppc_fn_call_count++;
  for (int __w = 0; __w < ARKCHEMY_WATCH_SLOTS; __w++) { if (g_ppc_current_pc == g_ppc_watch[__w].pc) { g_ppc_watch[__w].r3 = ctx->r[3]; g_ppc_watch[__w].r4 = ctx->r[4]; g_ppc_watch[__w].r5 = ctx->r[5]; g_ppc_watch[__w].r6 = ctx->r[6]; g_ppc_watch[__w].hit_count++; g_ppc_watch[__w].last_hit_call_count = g_ppc_fn_call_count; } }
  /* 0: stwu r1, -0x50(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)-80, ctx->r[1]);
  ctx->r[1] = ctx->r[1] + (int32_t)-80;
  /* 4: stw r31, 0x4c(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)76, ctx->r[31]);
  /* 8: mr r31, r1 */
  ctx->r[31] = ctx->r[1];
  /* c: lis r3, -0xf10 */
  ctx->r[3] = 61680u << 16;
  /* 10: ori r3, r3, 0xf0f0 */
  ctx->r[3] = ctx->r[3] | 61680u;
  /* 14: stw r3, 0x48(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)72, ctx->r[3]);
  /* 18: lis r3, 0xf0f */
  ctx->r[3] = 3855u << 16;
  /* 1c: ori r3, r3, 0xf0f */
  ctx->r[3] = ctx->r[3] | 3855u;
  /* 20: stw r3, 0x44(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)68, ctx->r[3]);
  /* 24: lwz r3, 0x48(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)72);
  /* 28: lwz r4, 0x44(r31) */
  ctx->r[4] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)68);
  /* 2c: and r3, r3, r4 */
  ctx->r[3] = ctx->r[3] & ctx->r[4];
  /* 30: stw r3, 0x40(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)64, ctx->r[3]);
  /* 34: lwz r3, 0x48(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)72);
  /* 38: lwz r4, 0x44(r31) */
  ctx->r[4] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)68);
  /* 3c: or r3, r3, r4 */
  ctx->r[3] = ctx->r[3] | ctx->r[4];
  /* 40: stw r3, 0x3c(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)60, ctx->r[3]);
  /* 44: lwz r3, 0x48(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)72);
  /* 48: lwz r4, 0x44(r31) */
  ctx->r[4] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)68);
  /* 4c: xor r3, r3, r4 */
  ctx->r[3] = ctx->r[3] ^ ctx->r[4];
  /* 50: stw r3, 0x38(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)56, ctx->r[3]);
  /* 54: lwz r3, 0x48(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)72);
  /* 58: lwz r4, 0x44(r31) */
  ctx->r[4] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)68);
  /* 5c: nor r3, r3, r4 */
  ctx->r[3] = ~(ctx->r[3] | ctx->r[4]);
  /* 60: stw r3, 0x34(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)52, ctx->r[3]);
  /* 64: lwz r3, 0x40(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)64);
  /* 68: nor r3, r3, r3 */
  ctx->r[3] = ~(ctx->r[3] | ctx->r[3]);
  /* 6c: stw r3, 0x30(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)48, ctx->r[3]);
  /* 70: lwz r3, 0x48(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)72);
  /* 74: slwi r3, r3, 4 */
  ctx->r[3] = ctx->r[3] << 4;
  /* 78: stw r3, 0x2c(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)44, ctx->r[3]);
  /* 7c: lwz r3, 0x48(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)72);
  /* 80: srwi r3, r3, 4 */
  ctx->r[3] = ctx->r[3] >> 4;
  /* 84: stw r3, 0x28(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)40, ctx->r[3]);
  /* 88: lwz r3, 0x48(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)72);
  /* 8c: srawi r3, r3, 4 */
  ctx->r[3] = (uint32_t)((int32_t)ctx->r[3] >> 4);
  /* 90: stw r3, 0x24(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)36, ctx->r[3]);
  /* 94: lwz r3, 0x3c(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)60);
  /* 98: stb r3, 0x20(r31) */
  ppc_store_u8(ctx, ctx->r[31] + (int32_t)32, (uint8_t)ctx->r[3]);
  /* 9c: lwz r3, 0x38(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)56);
  /* a0: srwi r3, r3, 8 */
  ctx->r[3] = ctx->r[3] >> 8;
  /* a4: stb r3, 0x21(r31) */
  ppc_store_u8(ctx, ctx->r[31] + (int32_t)33, (uint8_t)ctx->r[3]);
  /* a8: lbz r3, 0x20(r31) */
  ctx->r[3] = ppc_load_u8(ctx, ctx->r[31] + (int32_t)32);
  /* ac: stb r3, 0x1f(r31) */
  ppc_store_u8(ctx, ctx->r[31] + (int32_t)31, (uint8_t)ctx->r[3]);
  /* b0: lbz r3, 0x1f(r31) */
  ctx->r[3] = ppc_load_u8(ctx, ctx->r[31] + (int32_t)31);
  /* b4: extsb r3, r3 */
  ctx->r[3] = (uint32_t)(int32_t)(int8_t)ctx->r[3];
  /* b8: stw r3, 0x18(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)24, ctx->r[3]);
  /* bc: lwz r3, 0x2c(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)44);
  /* c0: sth r3, 0x14(r31) */
  ppc_store_u16(ctx, ctx->r[31] + (int32_t)20, (uint16_t)ctx->r[3]);
  /* c4: lhz r3, 0x14(r31) */
  ctx->r[3] = ppc_load_u16(ctx, ctx->r[31] + (int32_t)20);
  /* c8: sth r3, 0x12(r31) */
  ppc_store_u16(ctx, ctx->r[31] + (int32_t)18, (uint16_t)ctx->r[3]);
  /* cc: lha r3, 0x12(r31) */
  ctx->r[3] = (uint32_t)(int32_t)(int16_t)ppc_load_u16(ctx, ctx->r[31] + (int32_t)18);
  /* d0: stw r3, 0xc(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)12, ctx->r[3]);
  /* d4: lwz r3, 0x40(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)64);
  /* d8: lwz r4, 0x3c(r31) */
  ctx->r[4] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)60);
  /* dc: add r3, r3, r4 */
  ctx->r[3] = ctx->r[3] + ctx->r[4];
  /* e0: lwz r4, 0x38(r31) */
  ctx->r[4] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)56);
  /* e4: add r3, r3, r4 */
  ctx->r[3] = ctx->r[3] + ctx->r[4];
  /* e8: lwz r4, 0x34(r31) */
  ctx->r[4] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)52);
  /* ec: add r3, r3, r4 */
  ctx->r[3] = ctx->r[3] + ctx->r[4];
  /* f0: lwz r4, 0x30(r31) */
  ctx->r[4] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)48);
  /* f4: add r3, r3, r4 */
  ctx->r[3] = ctx->r[3] + ctx->r[4];
  /* f8: lwz r4, 0x2c(r31) */
  ctx->r[4] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)44);
  /* fc: add r3, r3, r4 */
  ctx->r[3] = ctx->r[3] + ctx->r[4];
  /* 100: lwz r4, 0x28(r31) */
  ctx->r[4] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)40);
  /* 104: add r3, r3, r4 */
  ctx->r[3] = ctx->r[3] + ctx->r[4];
  /* 108: lwz r4, 0x24(r31) */
  ctx->r[4] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)36);
  /* 10c: add r3, r3, r4 */
  ctx->r[3] = ctx->r[3] + ctx->r[4];
  /* 110: lwz r4, 0x18(r31) */
  ctx->r[4] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)24);
  /* 114: add r3, r3, r4 */
  ctx->r[3] = ctx->r[3] + ctx->r[4];
  /* 118: lwz r4, 0xc(r31) */
  ctx->r[4] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)12);
  /* 11c: add r3, r3, r4 */
  ctx->r[3] = ctx->r[3] + ctx->r[4];
  /* 120: stw r3, 8(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)8, ctx->r[3]);
  /* 124: lwz r3, 8(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)8);
  /* 128: lwz r31, 0x4c(r1) */
  ctx->r[31] = ppc_load_u32(ctx, ctx->r[1] + (int32_t)76);
  /* 12c: addi r1, r1, 0x50 */
  ctx->r[1] = ctx->r[1] + (uint32_t)(int32_t)80;
  /* 130: blr  */
  return;
}
