/* Generated by Arkchemy's recomp tool. Do not edit by hand. */
#include "ppc_runtime.h"

void t15_fcmp_compute(PpcContext *ctx);
void t15_fcmp_dispatch(PpcContext *ctx, uint32_t addr);

void t15_fcmp_init_globals(PpcContext *ctx) {
}

void t15_fcmp_run_static_initializers(PpcContext *ctx) {
}

void t15_fcmp_dispatch(PpcContext *ctx, uint32_t addr) {
  switch (addr) {
    case 0u: t15_fcmp_compute(ctx); return;
  }
}

void t15_fcmp_compute(PpcContext *ctx) {
  g_ppc_last_caller_lr = ctx->lr;
  g_ppc_current_pc = 0x0u; g_ppc_fn_call_count++;
  for (int __w = 0; __w < ARKCHEMY_WATCH_SLOTS; __w++) { if (g_ppc_current_pc == g_ppc_watch[__w].pc) { g_ppc_watch[__w].r3 = ctx->r[3]; g_ppc_watch[__w].r4 = ctx->r[4]; g_ppc_watch[__w].r5 = ctx->r[5]; g_ppc_watch[__w].r6 = ctx->r[6]; g_ppc_watch[__w].hit_count++; g_ppc_watch[__w].last_hit_call_count = g_ppc_fn_call_count; } }
  /* 0: stwu r1, -0x20(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)-32, ctx->r[1]);
  ctx->r[1] = ctx->r[1] + (int32_t)-32;
  /* 4: stw r31, 0x1c(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)28, ctx->r[31]);
  /* 8: mr r31, r1 */
  ctx->r[31] = ctx->r[1];
  /* c: stfs f1, 0x14(r31) */
  ppc_store_f32(ctx, ctx->r[31] + (int32_t)20, ctx->f[1]);
  /* 10: stfs f2, 0x10(r31) */
  ppc_store_f32(ctx, ctx->r[31] + (int32_t)16, ctx->f[2]);
  /* 14: lfs f0, 0x14(r31) */
  ctx->f[0] = (double)ppc_load_f32(ctx, ctx->r[31] + (int32_t)20);
  /* 18: lfs f1, 0x10(r31) */
  ctx->f[1] = (double)ppc_load_f32(ctx, ctx->r[31] + (int32_t)16);
  /* 1c: fcmpu cr0, f0, f1 */
  ppc_fcmpu(ctx, ctx->f[0], ctx->f[1]);
  /* 20: bge 0x3c */
  if ((ctx->cr0_gt || ctx->cr0_eq)) goto L_3c;
  /* 24: b 0x28 */
  goto L_28;
  L_28: ;
  /* 28: lfs f0, 0x14(r31) */
  ctx->f[0] = (double)ppc_load_f32(ctx, ctx->r[31] + (int32_t)20);
  /* 2c: lfs f1, 0x10(r31) */
  ctx->f[1] = (double)ppc_load_f32(ctx, ctx->r[31] + (int32_t)16);
  /* 30: fsubs f0, f0, f1 */
  ctx->f[0] = ppc_frsp(ctx->f[0] - ctx->f[1]);
  /* 34: stfs f0, 0x18(r31) */
  ppc_store_f32(ctx, ctx->r[31] + (int32_t)24, ctx->f[0]);
  /* 38: b 0x74 */
  goto L_74;
  L_3c: ;
  /* 3c: lfs f0, 0x14(r31) */
  ctx->f[0] = (double)ppc_load_f32(ctx, ctx->r[31] + (int32_t)20);
  /* 40: lfs f1, 0x10(r31) */
  ctx->f[1] = (double)ppc_load_f32(ctx, ctx->r[31] + (int32_t)16);
  /* 44: fcmpu cr0, f0, f1 */
  ppc_fcmpu(ctx, ctx->f[0], ctx->f[1]);
  /* 48: ble 0x64 */
  if ((ctx->cr0_lt || ctx->cr0_eq)) goto L_64;
  /* 4c: b 0x50 */
  goto L_50;
  L_50: ;
  /* 50: lfs f0, 0x14(r31) */
  ctx->f[0] = (double)ppc_load_f32(ctx, ctx->r[31] + (int32_t)20);
  /* 54: lfs f1, 0x10(r31) */
  ctx->f[1] = (double)ppc_load_f32(ctx, ctx->r[31] + (int32_t)16);
  /* 58: fadds f0, f0, f1 */
  ctx->f[0] = ppc_frsp(ctx->f[0] + ctx->f[1]);
  /* 5c: stfs f0, 0x18(r31) */
  ppc_store_f32(ctx, ctx->r[31] + (int32_t)24, ctx->f[0]);
  /* 60: b 0x74 */
  goto L_74;
  L_64: ;
  /* 64: b 0x68 */
  goto L_68;
  L_68: ;
  /* 68: li r3, 0 */
  ctx->r[3] = (uint32_t)(int32_t)0;
  /* 6c: stw r3, 0x18(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)24, ctx->r[3]);
  /* 70: b 0x74 */
  goto L_74;
  L_74: ;
  /* 74: lfs f1, 0x18(r31) */
  ctx->f[1] = (double)ppc_load_f32(ctx, ctx->r[31] + (int32_t)24);
  /* 78: lwz r31, 0x1c(r1) */
  ctx->r[31] = ppc_load_u32(ctx, ctx->r[1] + (int32_t)28);
  /* 7c: addi r1, r1, 0x20 */
  ctx->r[1] = ctx->r[1] + (uint32_t)(int32_t)32;
  /* 80: blr  */
  return;
}
