/* Generated by Arkchemy's recomp tool. Do not edit by hand. */
#include "ppc_runtime.h"

void t18_misc_bitops_compute(PpcContext *ctx);
void t18_misc_bitops_dispatch(PpcContext *ctx, uint32_t addr);

void t18_misc_bitops_init_globals(PpcContext *ctx) {
}

void t18_misc_bitops_run_static_initializers(PpcContext *ctx) {
}

void t18_misc_bitops_dispatch(PpcContext *ctx, uint32_t addr) {
  switch (addr) {
    case 0u: t18_misc_bitops_compute(ctx); return;
  }
}

void t18_misc_bitops_compute(PpcContext *ctx) {
  g_ppc_last_caller_lr = ctx->lr;
  g_ppc_current_pc = 0x0u; g_ppc_fn_call_count++;
  for (int __w = 0; __w < ARKCHEMY_WATCH_SLOTS; __w++) { if (g_ppc_current_pc == g_ppc_watch[__w].pc) { g_ppc_watch[__w].r3 = ctx->r[3]; g_ppc_watch[__w].r4 = ctx->r[4]; g_ppc_watch[__w].r5 = ctx->r[5]; g_ppc_watch[__w].r6 = ctx->r[6]; g_ppc_watch[__w].hit_count++; g_ppc_watch[__w].last_hit_call_count = g_ppc_fn_call_count; } }
  /* 0: stwu r1, -0x30(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)-48, ctx->r[1]);
  ctx->r[1] = ctx->r[1] + (int32_t)-48;
  /* 4: stw r31, 0x2c(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)44, ctx->r[31]);
  /* 8: mr r31, r1 */
  ctx->r[31] = ctx->r[1];
  /* c: stw r3, 0x28(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)40, ctx->r[3]);
  /* 10: stw r4, 0x24(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)36, ctx->r[4]);
  /* 14: lwz r3, 0x28(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)40);
  /* 18: ori r3, r3, 1 */
  ctx->r[3] = ctx->r[3] | 1u;
  /* 1c: cntlzw r3, r3 */
  ctx->r[3] = ppc_cntlzw(ctx->r[3]);
  /* 20: stw r3, 0x20(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)32, ctx->r[3]);
  /* 24: lwz r3, 0x28(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)40);
  /* 28: lwz r4, 0x24(r31) */
  ctx->r[4] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)36);
  /* 2c: andc r3, r3, r4 */
  ctx->r[3] = ctx->r[3] & ~ctx->r[4];
  /* 30: stw r3, 0x1c(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)28, ctx->r[3]);
  /* 34: lwz r3, 0x28(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)40);
  /* 38: lwz r4, 0x24(r31) */
  ctx->r[4] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)36);
  /* 3c: eqv r3, r3, r4 */
  ctx->r[3] = ~(ctx->r[3] ^ ctx->r[4]);
  /* 40: stw r3, 0x18(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)24, ctx->r[3]);
  /* 44: lwz r3, 0x28(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)40);
  /* 48: subfic r3, r3, 0x3e8 */
  ctx->r[3] = ppc_subfic(ctx, ctx->r[3], 1000);
  /* 4c: stw r3, 0x14(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)20, ctx->r[3]);
  /* 50: lwz r3, 0x20(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)32);
  /* 54: lwz r4, 0x1c(r31) */
  ctx->r[4] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)28);
  /* 58: add r3, r3, r4 */
  ctx->r[3] = ctx->r[3] + ctx->r[4];
  /* 5c: lwz r4, 0x18(r31) */
  ctx->r[4] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)24);
  /* 60: add r3, r3, r4 */
  ctx->r[3] = ctx->r[3] + ctx->r[4];
  /* 64: lwz r4, 0x14(r31) */
  ctx->r[4] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)20);
  /* 68: add r3, r3, r4 */
  ctx->r[3] = ctx->r[3] + ctx->r[4];
  /* 6c: lwz r31, 0x2c(r1) */
  ctx->r[31] = ppc_load_u32(ctx, ctx->r[1] + (int32_t)44);
  /* 70: addi r1, r1, 0x30 */
  ctx->r[1] = ctx->r[1] + (uint32_t)(int32_t)48;
  /* 74: blr  */
  return;
}
