/* Generated by Arkchemy's recomp tool. Do not edit by hand. */
#include "ppc_runtime.h"

void t22_manyargs_sum9(PpcContext *ctx);
void t22_manyargs_compute(PpcContext *ctx);
void t22_manyargs_dispatch(PpcContext *ctx, uint32_t addr);

void t22_manyargs_init_globals(PpcContext *ctx) {
}

void t22_manyargs_run_static_initializers(PpcContext *ctx) {
}

void t22_manyargs_dispatch(PpcContext *ctx, uint32_t addr) {
  switch (addr) {
    case 0u: t22_manyargs_sum9(ctx); return;
    case 128u: t22_manyargs_compute(ctx); return;
  }
}

void t22_manyargs_sum9(PpcContext *ctx) {
  g_ppc_last_caller_lr = ctx->lr;
  g_ppc_current_pc = 0x0u; g_ppc_fn_call_count++;
  for (int __w = 0; __w < ARKCHEMY_WATCH_SLOTS; __w++) { if (g_ppc_current_pc == g_ppc_watch[__w].pc) { g_ppc_watch[__w].r3 = ctx->r[3]; g_ppc_watch[__w].r4 = ctx->r[4]; g_ppc_watch[__w].r5 = ctx->r[5]; g_ppc_watch[__w].r6 = ctx->r[6]; g_ppc_watch[__w].hit_count++; g_ppc_watch[__w].last_hit_call_count = g_ppc_fn_call_count; } }
  /* 0: stwu r1, -0x30(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)-48, ctx->r[1]);
  ctx->r[1] = ctx->r[1] + (int32_t)-48;
  /* 4: stw r31, 0x2c(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)44, ctx->r[31]);
  /* 8: mr r31, r1 */
  ctx->r[31] = ctx->r[1];
  /* c: lwz r11, 0x38(r31) */
  ctx->r[11] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)56);
  /* 10: stw r3, 0x28(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)40, ctx->r[3]);
  /* 14: stw r4, 0x24(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)36, ctx->r[4]);
  /* 18: stw r5, 0x20(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)32, ctx->r[5]);
  /* 1c: stw r6, 0x1c(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)28, ctx->r[6]);
  /* 20: stw r7, 0x18(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)24, ctx->r[7]);
  /* 24: stw r8, 0x14(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)20, ctx->r[8]);
  /* 28: stw r9, 0x10(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)16, ctx->r[9]);
  /* 2c: stw r10, 0xc(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)12, ctx->r[10]);
  /* 30: lwz r3, 0x28(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)40);
  /* 34: lwz r4, 0x24(r31) */
  ctx->r[4] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)36);
  /* 38: add r3, r3, r4 */
  ctx->r[3] = ctx->r[3] + ctx->r[4];
  /* 3c: lwz r4, 0x20(r31) */
  ctx->r[4] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)32);
  /* 40: add r3, r3, r4 */
  ctx->r[3] = ctx->r[3] + ctx->r[4];
  /* 44: lwz r4, 0x1c(r31) */
  ctx->r[4] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)28);
  /* 48: add r3, r3, r4 */
  ctx->r[3] = ctx->r[3] + ctx->r[4];
  /* 4c: lwz r4, 0x18(r31) */
  ctx->r[4] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)24);
  /* 50: add r3, r3, r4 */
  ctx->r[3] = ctx->r[3] + ctx->r[4];
  /* 54: lwz r4, 0x14(r31) */
  ctx->r[4] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)20);
  /* 58: add r3, r3, r4 */
  ctx->r[3] = ctx->r[3] + ctx->r[4];
  /* 5c: lwz r4, 0x10(r31) */
  ctx->r[4] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)16);
  /* 60: add r3, r3, r4 */
  ctx->r[3] = ctx->r[3] + ctx->r[4];
  /* 64: lwz r4, 0xc(r31) */
  ctx->r[4] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)12);
  /* 68: add r3, r3, r4 */
  ctx->r[3] = ctx->r[3] + ctx->r[4];
  /* 6c: lwz r4, 0x38(r31) */
  ctx->r[4] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)56);
  /* 70: add r3, r3, r4 */
  ctx->r[3] = ctx->r[3] + ctx->r[4];
  /* 74: lwz r31, 0x2c(r1) */
  ctx->r[31] = ppc_load_u32(ctx, ctx->r[1] + (int32_t)44);
  /* 78: addi r1, r1, 0x30 */
  ctx->r[1] = ctx->r[1] + (uint32_t)(int32_t)48;
  /* 7c: blr  */
  return;
}
void t22_manyargs_compute(PpcContext *ctx) {
  g_ppc_last_caller_lr = ctx->lr;
  g_ppc_current_pc = 0x80u; g_ppc_fn_call_count++;
  for (int __w = 0; __w < ARKCHEMY_WATCH_SLOTS; __w++) { if (g_ppc_current_pc == g_ppc_watch[__w].pc) { g_ppc_watch[__w].r3 = ctx->r[3]; g_ppc_watch[__w].r4 = ctx->r[4]; g_ppc_watch[__w].r5 = ctx->r[5]; g_ppc_watch[__w].r6 = ctx->r[6]; g_ppc_watch[__w].hit_count++; g_ppc_watch[__w].last_hit_call_count = g_ppc_fn_call_count; } }
  /* 80: mflr r0 */
  ctx->r[0] = ctx->lr;
  /* 84: stwu r1, -0x10(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)-16, ctx->r[1]);
  ctx->r[1] = ctx->r[1] + (int32_t)-16;
  /* 88: stw r31, 0xc(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)12, ctx->r[31]);
  /* 8c: stw r0, 0x14(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)20, ctx->r[0]);
  /* 90: mr r31, r1 */
  ctx->r[31] = ctx->r[1];
  /* 94: li r3, 9 */
  ctx->r[3] = (uint32_t)(int32_t)9;
  /* 98: stw r3, 8(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)8, ctx->r[3]);
  /* 9c: li r3, 1 */
  ctx->r[3] = (uint32_t)(int32_t)1;
  /* a0: li r4, 2 */
  ctx->r[4] = (uint32_t)(int32_t)2;
  /* a4: li r5, 3 */
  ctx->r[5] = (uint32_t)(int32_t)3;
  /* a8: li r6, 4 */
  ctx->r[6] = (uint32_t)(int32_t)4;
  /* ac: li r7, 5 */
  ctx->r[7] = (uint32_t)(int32_t)5;
  /* b0: li r8, 6 */
  ctx->r[8] = (uint32_t)(int32_t)6;
  /* b4: li r9, 7 */
  ctx->r[9] = (uint32_t)(int32_t)7;
  /* b8: li r10, 8 */
  ctx->r[10] = (uint32_t)(int32_t)8;
  /* bc: bl 0xbc */
  ctx->lr = 0xc0u;
  t22_manyargs_sum9(ctx);
  /* c0: lwz r0, 0x14(r1) */
  ctx->r[0] = ppc_load_u32(ctx, ctx->r[1] + (int32_t)20);
  /* c4: lwz r31, 0xc(r1) */
  ctx->r[31] = ppc_load_u32(ctx, ctx->r[1] + (int32_t)12);
  /* c8: addi r1, r1, 0x10 */
  ctx->r[1] = ctx->r[1] + (uint32_t)(int32_t)16;
  /* cc: mtlr r0 */
  ctx->lr = ctx->r[0];
  /* d0: blr  */
  return;
}
