/* Generated by Arkchemy's recomp tool. Do not edit by hand. */
#include "ppc_runtime.h"

void t19_mixed_double_compute(PpcContext *ctx);
void t19_mixed_double_dispatch(PpcContext *ctx, uint32_t addr);

void t19_mixed_double_init_globals(PpcContext *ctx) {
  ppc_store_u8(ctx, 8196u, 89);
  ppc_store_u8(ctx, 8197u, 128);
  ppc_store_u8(ctx, 8199u, 4);
}

void t19_mixed_double_run_static_initializers(PpcContext *ctx) {
}

void t19_mixed_double_dispatch(PpcContext *ctx, uint32_t addr) {
  switch (addr) {
    case 0u: t19_mixed_double_compute(ctx); return;
  }
}

void t19_mixed_double_compute(PpcContext *ctx) {
  g_ppc_last_caller_lr = ctx->lr;
  g_ppc_current_pc = 0x0u; g_ppc_fn_call_count++;
  for (int __w = 0; __w < ARKCHEMY_WATCH_SLOTS; __w++) { if (g_ppc_current_pc == g_ppc_watch[__w].pc) { g_ppc_watch[__w].r3 = ctx->r[3]; g_ppc_watch[__w].r4 = ctx->r[4]; g_ppc_watch[__w].r5 = ctx->r[5]; g_ppc_watch[__w].r6 = ctx->r[6]; g_ppc_watch[__w].hit_count++; g_ppc_watch[__w].last_hit_call_count = g_ppc_fn_call_count; } }
  /* 0: stwu r1, -0x40(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)-64, ctx->r[1]);
  ctx->r[1] = ctx->r[1] + (int32_t)-64;
  /* 4: stw r31, 0x3c(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)60, ctx->r[31]);
  /* 8: mr r31, r1 */
  ctx->r[31] = ctx->r[1];
  /* c: stfd f1, 0x30(r31) */
  ppc_store_f64(ctx, ctx->r[31] + (int32_t)48, ctx->f[1]);
  /* 10: stw r3, 0x2c(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)44, ctx->r[3]);
  /* 14: stw r4, 0x28(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)40, ctx->r[4]);
  /* 18: li r3, 0 */
  ctx->r[3] = (uint32_t)(int32_t)0;
  /* 1c: stw r3, 0x24(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)36, ctx->r[3]);
  /* 20: stw r3, 0x20(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)32, ctx->r[3]);
  /* 24: stw r3, 0x1c(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)28, ctx->r[3]);
  /* 28: b 0x2c */
  goto L_2c;
  L_2c: ;
  /* 2c: lwz r3, 0x1c(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)28);
  /* 30: lwz r4, 0x28(r31) */
  ctx->r[4] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)40);
  /* 34: cmpw r3, r4 */
  ppc_cmpw(ctx, (int32_t)ctx->r[3], (int32_t)ctx->r[4]);
  /* 38: bge 0x90 */
  if ((ctx->cr0_gt || ctx->cr0_eq)) goto L_90;
  /* 3c: b 0x40 */
  goto L_40;
  L_40: ;
  /* 40: lwz r3, 0x2c(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)44);
  /* 44: lwz r4, 0x1c(r31) */
  ctx->r[4] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)28);
  /* 48: slwi r4, r4, 2 */
  ctx->r[4] = ctx->r[4] << 2;
  /* 4c: lwzx r3, r3, r4 */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[3] + ctx->r[4]);
  /* 50: lis r4, 0x4330 */
  ctx->r[4] = 17200u << 16;
  /* 54: stw r4, 8(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)8, ctx->r[4]);
  /* 58: xoris r3, r3, 0x8000 */
  ctx->r[3] = ctx->r[3] ^ (32768u << 16);
  /* 5c: stw r3, 0xc(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)12, ctx->r[3]);
  /* 60: lfd f0, 8(r31) */
  ctx->f[0] = ppc_load_f64(ctx, ctx->r[31] + (int32_t)8);
  /* 64: lis r3, 0 */
  ctx->r[3] = 8196u; /* &.rodata.cst4+4 */
  /* 68: lfs f1, 0(r3) */
  ctx->f[1] = (double)ppc_load_f32(ctx, ctx->r[3]);
  /* 6c: fsub f1, f0, f1 */
  ctx->f[1] = ctx->f[0] - ctx->f[1];
  /* 70: lfd f0, 0x20(r31) */
  ctx->f[0] = ppc_load_f64(ctx, ctx->r[31] + (int32_t)32);
  /* 74: fadd f0, f0, f1 */
  ctx->f[0] = ctx->f[0] + ctx->f[1];
  /* 78: stfd f0, 0x20(r31) */
  ppc_store_f64(ctx, ctx->r[31] + (int32_t)32, ctx->f[0]);
  /* 7c: b 0x80 */
  goto L_80;
  L_80: ;
  /* 80: lwz r3, 0x1c(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)28);
  /* 84: addi r3, r3, 1 */
  ctx->r[3] = ctx->r[3] + (uint32_t)(int32_t)1;
  /* 88: stw r3, 0x1c(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)28, ctx->r[3]);
  /* 8c: b 0x2c */
  goto L_2c;
  L_90: ;
  /* 90: lfd f0, 0x30(r31) */
  ctx->f[0] = ppc_load_f64(ctx, ctx->r[31] + (int32_t)48);
  /* 94: stfd f0, 0x10(r31) */
  ppc_store_f64(ctx, ctx->r[31] + (int32_t)16, ctx->f[0]);
  /* 98: lfd f0, 0x10(r31) */
  ctx->f[0] = ppc_load_f64(ctx, ctx->r[31] + (int32_t)16);
  /* 9c: lis r3, 0 */
  ctx->r[3] = 8192u; /* &.rodata.cst4+0 */
  /* a0: lfs f1, 0(r3) */
  ctx->f[1] = (double)ppc_load_f32(ctx, ctx->r[3]);
  /* a4: fcmpu cr0, f0, f1 */
  ppc_fcmpu(ctx, ctx->f[0], ctx->f[1]);
  /* a8: bge 0xc0 */
  if ((ctx->cr0_gt || ctx->cr0_eq)) goto L_c0;
  /* ac: b 0xb0 */
  goto L_b0;
  L_b0: ;
  /* b0: lfd f0, 0x10(r31) */
  ctx->f[0] = ppc_load_f64(ctx, ctx->r[31] + (int32_t)16);
  /* b4: fneg f0, f0 */
  ctx->f[0] = -ctx->f[0];
  /* b8: stfd f0, 0x10(r31) */
  ppc_store_f64(ctx, ctx->r[31] + (int32_t)16, ctx->f[0]);
  /* bc: b 0xc0 */
  goto L_c0;
  L_c0: ;
  /* c0: lfd f0, 0x20(r31) */
  ctx->f[0] = ppc_load_f64(ctx, ctx->r[31] + (int32_t)32);
  /* c4: lfd f1, 0x10(r31) */
  ctx->f[1] = ppc_load_f64(ctx, ctx->r[31] + (int32_t)16);
  /* c8: fadd f1, f0, f1 */
  ctx->f[1] = ctx->f[0] + ctx->f[1];
  /* cc: lwz r31, 0x3c(r1) */
  ctx->r[31] = ppc_load_u32(ctx, ctx->r[1] + (int32_t)60);
  /* d0: addi r1, r1, 0x40 */
  ctx->r[1] = ctx->r[1] + (uint32_t)(int32_t)64;
  /* d4: blr  */
  return;
}
