/* Generated by Arkchemy's recomp tool. Do not edit by hand. */
#include "ppc_runtime.h"

void t8_addis_frsp_compute(PpcContext *ctx);
void t8_addis_frsp_dispatch(PpcContext *ctx, uint32_t addr);

void t8_addis_frsp_init_globals(PpcContext *ctx) {
  ppc_store_u8(ctx, 8192u, 89);
  ppc_store_u8(ctx, 8193u, 128);
}

void t8_addis_frsp_run_static_initializers(PpcContext *ctx) {
}

void t8_addis_frsp_dispatch(PpcContext *ctx, uint32_t addr) {
  switch (addr) {
    case 0u: t8_addis_frsp_compute(ctx); return;
  }
}

void t8_addis_frsp_compute(PpcContext *ctx) {
  g_ppc_last_caller_lr = ctx->lr;
  g_ppc_current_pc = 0x0u; g_ppc_fn_call_count++;
  for (int __w = 0; __w < ARKCHEMY_WATCH_SLOTS; __w++) { if (g_ppc_current_pc == g_ppc_watch[__w].pc) { g_ppc_watch[__w].r3 = ctx->r[3]; g_ppc_watch[__w].r4 = ctx->r[4]; g_ppc_watch[__w].r5 = ctx->r[5]; g_ppc_watch[__w].r6 = ctx->r[6]; g_ppc_watch[__w].hit_count++; g_ppc_watch[__w].last_hit_call_count = g_ppc_fn_call_count; } }
  /* 0: stwu r1, -0x20(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)-32, ctx->r[1]);
  ctx->r[1] = ctx->r[1] + (int32_t)-32;
  /* 4: stw r31, 0x1c(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)28, ctx->r[31]);
  /* 8: mr r31, r1 */
  ctx->r[31] = ctx->r[1];
  /* c: lis r4, 0x4330 */
  ctx->r[4] = 17200u << 16;
  /* 10: addis r3, r3, 5 */
  ctx->r[3] = ctx->r[3] + (5u << 16);
  /* 14: stw r4, 0x10(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)16, ctx->r[4]);
  /* 18: frsp f1, f1 */
  ctx->f[1] = ppc_frsp(ctx->f[1]);
  /* 1c: stw r3, 0x14(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)20, ctx->r[3]);
  /* 20: lis r3, 0 */
  ctx->r[3] = 8192u; /* &.rodata.cst4+0 */
  /* 24: lfd f0, 0x10(r31) */
  ctx->f[0] = ppc_load_f64(ctx, ctx->r[31] + (int32_t)16);
  /* 28: lfs f2, 0(r3) */
  ctx->f[2] = (double)ppc_load_f32(ctx, ctx->r[3]);
  /* 2c: lwz r31, 0x1c(r1) */
  ctx->r[31] = ppc_load_u32(ctx, ctx->r[1] + (int32_t)28);
  /* 30: fsub f0, f0, f2 */
  ctx->f[0] = ctx->f[0] - ctx->f[2];
  /* 34: fadd f1, f1, f0 */
  ctx->f[1] = ctx->f[1] + ctx->f[0];
  /* 38: addi r1, r1, 0x20 */
  ctx->r[1] = ctx->r[1] + (uint32_t)(int32_t)32;
  /* 3c: blr  */
  return;
}
