/* Generated by Arkchemy's recomp tool. Do not edit by hand. */
#include "ppc_runtime.h"

void t17_double_compute(PpcContext *ctx);
void t17_double_dispatch(PpcContext *ctx, uint32_t addr);

void t17_double_init_globals(PpcContext *ctx) {
  ppc_store_u8(ctx, 8192u, 89);
  ppc_store_u8(ctx, 8193u, 128);
  ppc_store_u8(ctx, 8195u, 4);
}

void t17_double_run_static_initializers(PpcContext *ctx) {
}

void t17_double_dispatch(PpcContext *ctx, uint32_t addr) {
  switch (addr) {
    case 0u: t17_double_compute(ctx); return;
  }
}

void t17_double_compute(PpcContext *ctx) {
  g_ppc_last_caller_lr = ctx->lr;
  g_ppc_current_pc = 0x0u; g_ppc_fn_call_count++;
  for (int __w = 0; __w < ARKCHEMY_WATCH_SLOTS; __w++) { if (g_ppc_current_pc == g_ppc_watch[__w].pc) { g_ppc_watch[__w].r3 = ctx->r[3]; g_ppc_watch[__w].r4 = ctx->r[4]; g_ppc_watch[__w].r5 = ctx->r[5]; g_ppc_watch[__w].r6 = ctx->r[6]; g_ppc_watch[__w].hit_count++; g_ppc_watch[__w].last_hit_call_count = g_ppc_fn_call_count; } }
  /* 0: stwu r1, -0x50(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)-80, ctx->r[1]);
  ctx->r[1] = ctx->r[1] + (int32_t)-80;
  /* 4: stw r31, 0x4c(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)76, ctx->r[31]);
  /* 8: mr r31, r1 */
  ctx->r[31] = ctx->r[1];
  /* c: stfd f1, 0x40(r31) */
  ppc_store_f64(ctx, ctx->r[31] + (int32_t)64, ctx->f[1]);
  /* 10: stfd f2, 0x38(r31) */
  ppc_store_f64(ctx, ctx->r[31] + (int32_t)56, ctx->f[2]);
  /* 14: lfd f0, 0x40(r31) */
  ctx->f[0] = ppc_load_f64(ctx, ctx->r[31] + (int32_t)64);
  /* 18: lfd f1, 0x38(r31) */
  ctx->f[1] = ppc_load_f64(ctx, ctx->r[31] + (int32_t)56);
  /* 1c: fadd f0, f0, f1 */
  ctx->f[0] = ctx->f[0] + ctx->f[1];
  /* 20: stfd f0, 0x30(r31) */
  ppc_store_f64(ctx, ctx->r[31] + (int32_t)48, ctx->f[0]);
  /* 24: lfd f0, 0x40(r31) */
  ctx->f[0] = ppc_load_f64(ctx, ctx->r[31] + (int32_t)64);
  /* 28: lfd f1, 0x38(r31) */
  ctx->f[1] = ppc_load_f64(ctx, ctx->r[31] + (int32_t)56);
  /* 2c: lfd f2, 0x30(r31) */
  ctx->f[2] = ppc_load_f64(ctx, ctx->r[31] + (int32_t)48);
  /* 30: fmsub f0, f0, f1, f2 */
  ctx->f[0] = ctx->f[0] * ctx->f[1] - ctx->f[2];
  /* 34: stfd f0, 0x28(r31) */
  ppc_store_f64(ctx, ctx->r[31] + (int32_t)40, ctx->f[0]);
  /* 38: lfd f0, 0x28(r31) */
  ctx->f[0] = ppc_load_f64(ctx, ctx->r[31] + (int32_t)40);
  /* 3c: fctiwz f0, f0 */
  ctx->f[0] = ppc_fctiwz(ctx->f[0]);
  /* 40: stfd f0, 0x10(r31) */
  ppc_store_f64(ctx, ctx->r[31] + (int32_t)16, ctx->f[0]);
  /* 44: lwz r3, 0x14(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)20);
  /* 48: stw r3, 0x24(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)36, ctx->r[3]);
  /* 4c: lfd f0, 0x28(r31) */
  ctx->f[0] = ppc_load_f64(ctx, ctx->r[31] + (int32_t)40);
  /* 50: lwz r3, 0x24(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)36);
  /* 54: lis r4, 0x4330 */
  ctx->r[4] = 17200u << 16;
  /* 58: stw r4, 0x18(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)24, ctx->r[4]);
  /* 5c: xoris r3, r3, 0x8000 */
  ctx->r[3] = ctx->r[3] ^ (32768u << 16);
  /* 60: stw r3, 0x1c(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)28, ctx->r[3]);
  /* 64: lfd f1, 0x18(r31) */
  ctx->f[1] = ppc_load_f64(ctx, ctx->r[31] + (int32_t)24);
  /* 68: lis r3, 0 */
  ctx->r[3] = 8192u; /* &.rodata.cst4+0 */
  /* 6c: lfs f2, 0(r3) */
  ctx->f[2] = (double)ppc_load_f32(ctx, ctx->r[3]);
  /* 70: fsub f1, f1, f2 */
  ctx->f[1] = ctx->f[1] - ctx->f[2];
  /* 74: fadd f1, f0, f1 */
  ctx->f[1] = ctx->f[0] + ctx->f[1];
  /* 78: lwz r31, 0x4c(r1) */
  ctx->r[31] = ppc_load_u32(ctx, ctx->r[1] + (int32_t)76);
  /* 7c: addi r1, r1, 0x50 */
  ctx->r[1] = ctx->r[1] + (uint32_t)(int32_t)80;
  /* 80: blr  */
  return;
}
