/* Generated by Arkchemy's recomp tool. Do not edit by hand. */
#include "ppc_runtime.h"

void t23_multifile_compute(PpcContext *ctx);
void t23_multifile_helper(PpcContext *ctx); /* external -- defined in another translation unit */
void t23_multifile_b_dispatch(PpcContext *ctx, uint32_t addr);

void t23_multifile_b_init_globals(PpcContext *ctx) {
}

void t23_multifile_b_run_static_initializers(PpcContext *ctx) {
}

void t23_multifile_b_dispatch(PpcContext *ctx, uint32_t addr) {
  switch (addr) {
    case 0u: t23_multifile_compute(ctx); return;
  }
}

void t23_multifile_compute(PpcContext *ctx) {
  g_ppc_last_caller_lr = ctx->lr;
  g_ppc_current_pc = 0x0u; g_ppc_fn_call_count++;
  for (int __w = 0; __w < ARKCHEMY_WATCH_SLOTS; __w++) { if (g_ppc_current_pc == g_ppc_watch[__w].pc) { g_ppc_watch[__w].r3 = ctx->r[3]; g_ppc_watch[__w].r4 = ctx->r[4]; g_ppc_watch[__w].r5 = ctx->r[5]; g_ppc_watch[__w].r6 = ctx->r[6]; g_ppc_watch[__w].hit_count++; g_ppc_watch[__w].last_hit_call_count = g_ppc_fn_call_count; } }
  /* 0: mflr r0 */
  ctx->r[0] = ctx->lr;
  /* 4: stwu r1, -0x20(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)-32, ctx->r[1]);
  ctx->r[1] = ctx->r[1] + (int32_t)-32;
  /* 8: stw r31, 0x1c(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)28, ctx->r[31]);
  /* c: stw r0, 0x24(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)36, ctx->r[0]);
  /* 10: mr r31, r1 */
  ctx->r[31] = ctx->r[1];
  /* 14: stw r3, 0x18(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)24, ctx->r[3]);
  /* 18: li r3, 0 */
  ctx->r[3] = (uint32_t)(int32_t)0;
  /* 1c: stw r3, 0x14(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)20, ctx->r[3]);
  /* 20: stw r3, 0x10(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)16, ctx->r[3]);
  /* 24: b 0x28 */
  goto L_28;
  L_28: ;
  /* 28: lwz r3, 0x10(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)16);
  /* 2c: lwz r4, 0x18(r31) */
  ctx->r[4] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)24);
  /* 30: cmpw r3, r4 */
  ppc_cmpw(ctx, (int32_t)ctx->r[3], (int32_t)ctx->r[4]);
  /* 34: bge 0x68 */
  if ((ctx->cr0_gt || ctx->cr0_eq)) goto L_68;
  /* 38: b 0x3c */
  goto L_3c;
  L_3c: ;
  /* 3c: lwz r3, 0x10(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)16);
  /* 40: bl 0x40 */
  ctx->lr = 0x44u;
  t23_multifile_helper(ctx);
  /* 44: mr r4, r3 */
  ctx->r[4] = ctx->r[3];
  /* 48: lwz r3, 0x14(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)20);
  /* 4c: add r3, r3, r4 */
  ctx->r[3] = ctx->r[3] + ctx->r[4];
  /* 50: stw r3, 0x14(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)20, ctx->r[3]);
  /* 54: b 0x58 */
  goto L_58;
  L_58: ;
  /* 58: lwz r3, 0x10(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)16);
  /* 5c: addi r3, r3, 1 */
  ctx->r[3] = ctx->r[3] + (uint32_t)(int32_t)1;
  /* 60: stw r3, 0x10(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)16, ctx->r[3]);
  /* 64: b 0x28 */
  goto L_28;
  L_68: ;
  /* 68: lwz r3, 0x14(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)20);
  /* 6c: lwz r0, 0x24(r1) */
  ctx->r[0] = ppc_load_u32(ctx, ctx->r[1] + (int32_t)36);
  /* 70: lwz r31, 0x1c(r1) */
  ctx->r[31] = ppc_load_u32(ctx, ctx->r[1] + (int32_t)28);
  /* 74: addi r1, r1, 0x20 */
  ctx->r[1] = ctx->r[1] + (uint32_t)(int32_t)32;
  /* 78: mtlr r0 */
  ctx->lr = ctx->r[0];
  /* 7c: blr  */
  return;
}
