/* Generated by Arkchemy's recomp tool. Do not edit by hand. */
#include "ppc_runtime.h"

void t11_rotate_compute(PpcContext *ctx);
void t11_rotate_dispatch(PpcContext *ctx, uint32_t addr);

void t11_rotate_init_globals(PpcContext *ctx) {
}

void t11_rotate_run_static_initializers(PpcContext *ctx) {
}

void t11_rotate_dispatch(PpcContext *ctx, uint32_t addr) {
  switch (addr) {
    case 0u: t11_rotate_compute(ctx); return;
  }
}

void t11_rotate_compute(PpcContext *ctx) {
  g_ppc_last_caller_lr = ctx->lr;
  g_ppc_current_pc = 0x0u; g_ppc_fn_call_count++;
  for (int __w = 0; __w < ARKCHEMY_WATCH_SLOTS; __w++) { if (g_ppc_current_pc == g_ppc_watch[__w].pc) { g_ppc_watch[__w].r3 = ctx->r[3]; g_ppc_watch[__w].r4 = ctx->r[4]; g_ppc_watch[__w].r5 = ctx->r[5]; g_ppc_watch[__w].r6 = ctx->r[6]; g_ppc_watch[__w].hit_count++; g_ppc_watch[__w].last_hit_call_count = g_ppc_fn_call_count; } }
  /* 0: stwu r1, -0x10(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)-16, ctx->r[1]);
  ctx->r[1] = ctx->r[1] + (int32_t)-16;
  /* 4: stw r31, 0xc(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)12, ctx->r[31]);
  /* 8: mr r31, r1 */
  ctx->r[31] = ctx->r[1];
  /* c: cmpwi r3, 0 */
  ppc_cmpw(ctx, (int32_t)ctx->r[3], 0);
  /* 10: ble 0x34 */
  if ((ctx->cr0_lt || ctx->cr0_eq)) goto L_34;
  /* 14: addi r5, r3, -1 */
  ctx->r[5] = ctx->r[3] + (uint32_t)(int32_t)-1;
  /* 18: addi r6, r3, -2 */
  ctx->r[6] = ctx->r[3] + (uint32_t)(int32_t)-2;
  /* 1c: mullw r5, r5, r6 */
  ctx->r[5] = ctx->r[5] * ctx->r[6];
  /* 20: rlwinm r5, r5, 0, 0, 0x1e */
  ctx->r[5] = ctx->r[5] & 4294967294u;
  /* 24: mulli r4, r3, 3 */
  ctx->r[4] = ctx->r[3] * (uint32_t)(int32_t)3;
  /* 28: add r4, r4, r5 */
  ctx->r[4] = ctx->r[4] + ctx->r[5];
  /* 2c: addi r4, r4, -2 */
  ctx->r[4] = ctx->r[4] + (uint32_t)(int32_t)-2;
  /* 30: b 0x38 */
  goto L_38;
  L_34: ;
  /* 34: li r4, 0 */
  ctx->r[4] = (uint32_t)(int32_t)0;
  L_38: ;
  /* 38: lis r5, -0x61c9 */
  ctx->r[5] = 40503u << 16;
  /* 3c: ori r5, r5, 0x79b1 */
  ctx->r[5] = ctx->r[5] | 31153u;
  /* 40: lis r6, -0xe45 */
  ctx->r[6] = 61883u << 16;
  /* 44: mullw r5, r3, r5 */
  ctx->r[5] = ctx->r[3] * ctx->r[5];
  /* 48: ori r6, r6, 0xcd88 */
  ctx->r[6] = ctx->r[6] | 52616u;
  /* 4c: lwz r31, 0xc(r1) */
  ctx->r[31] = ppc_load_u32(ctx, ctx->r[1] + (int32_t)12);
  /* 50: mullw r3, r3, r6 */
  ctx->r[3] = ctx->r[3] * ctx->r[6];
  /* 54: clrlwi r6, r5, 0x1a */
  ctx->r[6] = ctx->r[5] & 63u;
  /* 58: srwi r5, r5, 0x1d */
  ctx->r[5] = ctx->r[5] >> 29;
  /* 5c: rlwimi r5, r3, 0, 0, 0x1c */
  ctx->r[5] = (ctx->r[3] & 4294967288u) | (ctx->r[5] & 7u);
  /* 60: add r3, r5, r6 */
  ctx->r[3] = ctx->r[5] + ctx->r[6];
  /* 64: add r3, r3, r4 */
  ctx->r[3] = ctx->r[3] + ctx->r[4];
  /* 68: addi r1, r1, 0x10 */
  ctx->r[1] = ctx->r[1] + (uint32_t)(int32_t)16;
  /* 6c: blr  */
  return;
}
