/* Generated by Bramble's recomp tool. Do not edit by hand. */
#include "ppc_runtime.h"

void t4_rodata_classify(PpcContext *ctx);
void t4_rodata_dispatch(PpcContext *ctx, uint32_t addr);

void t4_rodata_init_globals(PpcContext *ctx) {
  ppc_store_u8(ctx, 8195u, 7);
  ppc_store_u8(ctx, 8198u, 1);
  ppc_store_u8(ctx, 8199u, 44);
  ppc_store_u8(ctx, 8200u, 255);
  ppc_store_u8(ctx, 8201u, 255);
  ppc_store_u8(ctx, 8202u, 255);
  ppc_store_u8(ctx, 8203u, 237);
  ppc_store_u8(ctx, 8207u, 42);
  ppc_store_u8(ctx, 8210u, 3);
  ppc_store_u8(ctx, 8211u, 233);
  ppc_store_u8(ctx, 8215u, 5);
}

void t4_rodata_dispatch(PpcContext *ctx, uint32_t addr) {
  switch (addr) {
    case 0u: t4_rodata_classify(ctx); return;
  }
}

void t4_rodata_classify(PpcContext *ctx) {
  /* 0: cmplwi r3, 5 */
  ppc_cmplw(ctx, ctx->r[3], 5u);
  /* 4: li r4, -1 */
  ctx->r[4] = (uint32_t)(int32_t)-1;
  /* 8: bgt 0x1c */
  if (ctx->cr0_gt) goto L_1c;
  /* c: lis r4, 0 */
  ctx->r[4] = 8192u; /* &.rodata+0 */
  /* 10: slwi r3, r3, 2 */
  ctx->r[3] = ctx->r[3] << 2;
  /* 14: addi r4, r4, 0 */
  ctx->r[4] = ctx->r[4];
  /* 18: lwzx r4, r4, r3 */
  ctx->r[4] = ppc_load_u32(ctx, ctx->r[4] + ctx->r[3]);
  L_1c: ;
  /* 1c: mr r3, r4 */
  ctx->r[3] = ctx->r[4];
  /* 20: blr  */
  return;
}
