/* Generated by Arkchemy's recomp tool. Do not edit by hand. */
#include "ppc_runtime.h"

void t20_globals_compute(PpcContext *ctx);
void t20_globals_dispatch(PpcContext *ctx, uint32_t addr);

void t20_globals_init_globals(PpcContext *ctx) {
  ppc_store_u8(ctx, 8195u, 100);
  ppc_store_u8(ctx, 8199u, 10);
  ppc_store_u8(ctx, 8203u, 20);
  ppc_store_u8(ctx, 8207u, 30);
  ppc_store_u8(ctx, 8211u, 40);
}

void t20_globals_run_static_initializers(PpcContext *ctx) {
}

void t20_globals_dispatch(PpcContext *ctx, uint32_t addr) {
  switch (addr) {
    case 0u: t20_globals_compute(ctx); return;
  }
}

void t20_globals_compute(PpcContext *ctx) {
  g_ppc_last_caller_lr = ctx->lr;
  g_ppc_current_pc = 0x0u; g_ppc_fn_call_count++;
  for (int __w = 0; __w < ARKCHEMY_WATCH_SLOTS; __w++) { if (g_ppc_current_pc == g_ppc_watch[__w].pc) { g_ppc_watch[__w].r3 = ctx->r[3]; g_ppc_watch[__w].r4 = ctx->r[4]; g_ppc_watch[__w].r5 = ctx->r[5]; g_ppc_watch[__w].r6 = ctx->r[6]; g_ppc_watch[__w].hit_count++; g_ppc_watch[__w].last_hit_call_count = g_ppc_fn_call_count; } }
  /* 0: stwu r1, -0x10(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)-16, ctx->r[1]);
  ctx->r[1] = ctx->r[1] + (int32_t)-16;
  /* 4: stw r31, 0xc(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)12, ctx->r[31]);
  /* 8: mr r31, r1 */
  ctx->r[31] = ctx->r[1];
  /* c: stw r3, 8(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)8, ctx->r[3]);
  /* 10: lwz r5, 8(r31) */
  ctx->r[5] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)8);
  /* 14: lis r3, 0 */
  ctx->r[3] = 8192u; /* &.data+0 */
  /* 18: lwz r4, 0(r3) */
  ctx->r[4] = ppc_load_u32(ctx, ctx->r[3]);
  /* 1c: add r4, r4, r5 */
  ctx->r[4] = ctx->r[4] + ctx->r[5];
  /* 20: stw r4, 0(r3) */
  ppc_store_u32(ctx, ctx->r[3], ctx->r[4]);
  /* 24: lwz r3, 0(r3) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[3]);
  /* 28: lwz r5, 8(r31) */
  ctx->r[5] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)8);
  /* 2c: lis r4, 0 */
  ctx->r[4] = 8196u; /* &.data+4 */
  /* 30: addi r4, r4, 0 */
  ctx->r[4] = ctx->r[4];
  /* 34: rlwinm r5, r5, 2, 0x1c, 0x1d */
  ctx->r[5] = ppc_rotl32(ctx->r[5], 2) & 12u;
  /* 38: lwzx r4, r4, r5 */
  ctx->r[4] = ppc_load_u32(ctx, ctx->r[4] + ctx->r[5]);
  /* 3c: add r3, r3, r4 */
  ctx->r[3] = ctx->r[3] + ctx->r[4];
  /* 40: lwz r31, 0xc(r1) */
  ctx->r[31] = ppc_load_u32(ctx, ctx->r[1] + (int32_t)12);
  /* 44: addi r1, r1, 0x10 */
  ctx->r[1] = ctx->r[1] + (uint32_t)(int32_t)16;
  /* 48: blr  */
  return;
}
