/* Generated by Arkchemy's recomp tool. Do not edit by hand. */
#include "ppc_runtime.h"

void t13_division_compute(PpcContext *ctx);
void t13_division_dispatch(PpcContext *ctx, uint32_t addr);

void t13_division_init_globals(PpcContext *ctx) {
}

void t13_division_run_static_initializers(PpcContext *ctx) {
}

void t13_division_dispatch(PpcContext *ctx, uint32_t addr) {
  switch (addr) {
    case 0u: t13_division_compute(ctx); return;
  }
}

void t13_division_compute(PpcContext *ctx) {
  g_ppc_last_caller_lr = ctx->lr;
  g_ppc_current_pc = 0x0u; g_ppc_fn_call_count++;
  for (int __w = 0; __w < ARKCHEMY_WATCH_SLOTS; __w++) { if (g_ppc_current_pc == g_ppc_watch[__w].pc) { g_ppc_watch[__w].r3 = ctx->r[3]; g_ppc_watch[__w].r4 = ctx->r[4]; g_ppc_watch[__w].r5 = ctx->r[5]; g_ppc_watch[__w].r6 = ctx->r[6]; g_ppc_watch[__w].hit_count++; g_ppc_watch[__w].last_hit_call_count = g_ppc_fn_call_count; } }
  /* 0: stwu r1, -0x30(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)-48, ctx->r[1]);
  ctx->r[1] = ctx->r[1] + (int32_t)-48;
  /* 4: stw r31, 0x2c(r1) */
  ppc_store_u32(ctx, ctx->r[1] + (int32_t)44, ctx->r[31]);
  /* 8: mr r31, r1 */
  ctx->r[31] = ctx->r[1];
  /* c: stw r3, 0x28(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)40, ctx->r[3]);
  /* 10: stw r4, 0x24(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)36, ctx->r[4]);
  /* 14: stw r5, 0x20(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)32, ctx->r[5]);
  /* 18: stw r6, 0x1c(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)28, ctx->r[6]);
  /* 1c: lwz r3, 0x28(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)40);
  /* 20: lwz r4, 0x24(r31) */
  ctx->r[4] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)36);
  /* 24: divw r3, r3, r4 */
  ctx->r[3] = (uint32_t)((int32_t)ctx->r[3] / (int32_t)ctx->r[4]);
  /* 28: stw r3, 0x18(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)24, ctx->r[3]);
  /* 2c: lwz r3, 0x20(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)32);
  /* 30: lwz r4, 0x1c(r31) */
  ctx->r[4] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)28);
  /* 34: divwu r3, r3, r4 */
  ctx->r[3] = ctx->r[3] / ctx->r[4];
  /* 38: stw r3, 0x14(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)20, ctx->r[3]);
  /* 3c: lwz r4, 0x28(r31) */
  ctx->r[4] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)40);
  /* 40: lwz r5, 0x24(r31) */
  ctx->r[5] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)36);
  /* 44: divw r3, r4, r5 */
  ctx->r[3] = (uint32_t)((int32_t)ctx->r[4] / (int32_t)ctx->r[5]);
  /* 48: mullw r3, r3, r5 */
  ctx->r[3] = ctx->r[3] * ctx->r[5];
  /* 4c: subf r3, r3, r4 */
  ctx->r[3] = ctx->r[4] - ctx->r[3];
  /* 50: stw r3, 0x10(r31) */
  ppc_store_u32(ctx, ctx->r[31] + (int32_t)16, ctx->r[3]);
  /* 54: lwz r3, 0x18(r31) */
  ctx->r[3] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)24);
  /* 58: lwz r4, 0x14(r31) */
  ctx->r[4] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)20);
  /* 5c: add r3, r3, r4 */
  ctx->r[3] = ctx->r[3] + ctx->r[4];
  /* 60: lwz r4, 0x10(r31) */
  ctx->r[4] = ppc_load_u32(ctx, ctx->r[31] + (int32_t)16);
  /* 64: add r3, r3, r4 */
  ctx->r[3] = ctx->r[3] + ctx->r[4];
  /* 68: lwz r31, 0x2c(r1) */
  ctx->r[31] = ppc_load_u32(ctx, ctx->r[1] + (int32_t)44);
  /* 6c: addi r1, r1, 0x30 */
  ctx->r[1] = ctx->r[1] + (uint32_t)(int32_t)48;
  /* 70: blr  */
  return;
}
